### ISSUE TITLE
Idea: Would it be helpful to make this a Github Template repository?

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#1]
### Summary: 

The bigger question related to this idea is how we expect to use this template to start. Something we might eventually want to add a section in the README once the template is ready to go.  

It seems that the [main advantage toward using a template repository](https://hub.packtpub.com/github-introduces-template-repository-for-easy-boilerplate-code-management-and-distribution/) as compared to cloning or forking is that you would have a clean git history. This would probably be good since each course made from this template should probably have its own git history. 

#### How to create a template repository: 
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

**Comment by jtleek** [comment]
I think this is a great idea @carriewright11 can we make this a template repo?

**Comment by carriewright11** [comment]
Should be a template repo now. Thanks for the suggestion!
