### ISSUE TITLE
How do we want to manage software requirements

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#10]
This will be less relevant for courses that aren't as much code needing to be run, but will definitely be something we want to thinking about for courses with code that needs to be run.

I am most familiar with using Docker https://www.docker.com for this purpose. 

We would mainly use a Docker image and container for development but depending on the user target for a course, we could definitely offer our Docker image to the user as well.

**Comment by muschellij2** [comment]
I would think Docker would work but also having a script run on GitHub actions will likely be sufficient for some of the work.  Otherwise, I think we'd assume software would be installed locally.  Alternatively, it can be installed when run and then removed when the book is completed.

**Comment by cansavvy** [comment]
GitHub actions will work more nicely if we give it the same Docker image to run in as we are developing in. Plus this will give more consistency for package versions between developers and the GitHub actions.

Additionally when software dependency entanglements occur, we will only need to fix them once on the docket container as opposed to each individual having to fix the issue locally.

**Comment by cansavvy** [comment]
Docker image is made and up on docker hub. The instructions in [CONTRIBUTING.md](https://github.com/jhudsl/ITCR_Course_Template_Bookdown/blob/main/CONTRIBUTING.md#setting-up-docker-image) describe how to get started (But I still need to add more info on adding packages).
