### ISSUE TITLE
Remove YAML from chapter template?

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/OTTR_Template#103]
Currently the chapter templates have a short YAML header:

```
---
title: "Chapter title"
output: html_document
---
```

Should this be there?  My impression from looking through the `bookdown` reference is that the YAML should all go in the first file (`index.Rmd`) and the subsequent chapters should just start with the H1 header.  Also  a quick experiment looks like the chapters render fine without it, but I haven't tested that thoroughly.  Is this YAML being used somewhere in our pipeline that I'm not aware of, or can it go?

**Comment by cansavvy** [comment]
When you make an Rmd, I think that's default. If it doesn't hurt anything to remove it, we can. But it also doesn't hurt anything to leave it; so I don't feel inclined to put any instruction on it in particular. Unless there's a reason we should.

**Comment by KatherineCox** [comment]
It's mildly confusing 

- to have the `title` field if it's not actually being used for the title of your chapter
- to have YAML at all, when `bookdown` is telling me not to

But neither of those is a big deal, or in any way preventing me from writing my chapters.

If we make our own .Rmd template (i.e. File > New File > RMarkdown > From Template > DaSL Chapter) we could make one with no YAML.  But I wasn't sure if our YAML was there for a reason and was being used somewhere not immediately obvious to me.  Sounds like no.

**Comment by cansavvy** [comment]
Nope. It's not there for any reason I know of. I'm all for making a standard way of creating new Rmds if you want to figure that out and add it to the getting_started.md
