### ISSUE TITLE
Keeping different GHA options available in the template

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#108]
@cutsort made a simplified version of render-bookdown.yml which for courses that aren't running code and won't have to change the docker image might be a good option to have on hand.

Question is how to we have different GHA Options available for courses using this template without it getting disorganized and confusing?

**Comment by KatherineCox** [comment]
Related, it might be useful to separate out the instructions for DIY Docker images into a separate document from `getting_started`.  I.e. have `getting_started` explain the simplified version for courses that aren't running code (just use our standard Docker image), and then say "if you are running code, see this document for further instructions".

I don't know enough about how all this is working, but would it then be possible to have the simple version of `render-bookdown.yml` be the default, and have the instructions for "turning on" the more complicated version in that second set of instructions?

**Comment by cansavvy** [comment]
I think separating out instructions in some way for "code intensive" and "non-code intensive" courses is a great idea and I'm going to make a separate issue about this.

**Comment by cansavvy** [comment]
This has been addressed in #42
