### ISSUE TITLE
Create method of feedback

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#129]
We want to encourage feedback for all the courses! So we want it to be as easy as possible for people to file issues about courses (and in a way we can try to keep things organized). 

We can use Google forms that are linked to GitHub issues using Zapier zaps. This way having a GitHub account is not a barrier for someone to file an issue. 

The Google form should probably be rather general, but if there are specific questions we want to ask we should discuss it here.

Probably optionally allow people to leave their email if they are okay with us contacting them for more info.

**Comment by cansavvy** [comment]
Here's a draft: https://docs.google.com/forms/d/1PjaJEmpnaHgDS7PwIuKxoY8mX7ZwlneI0i6ciXa73cY/edit

**Comment by cansavvy** [comment]
Here's the sharing url: https://forms.gle/tESJ4eSps3N5hGK47

Working on the zap and how we incorporate this into every page in a way that's not horrible to maintain.

**Comment by cansavvy** [comment]
I think we should be able to add the link to the bookdown yaml in this template, but then we'll need a way to have it add somewhere to each page in leanpub.

**Comment by cansavvy** [comment]
@carriewright11 the bookdown yml part of this seems like something you might know how to do? Would you be able to do it or give me some hints on how you think it could be done?

**Comment by carriewright11** [comment]
Hi! sorry I had some meetings this morning. Yes, I could add this, but indeed this would require something different for the Leanpub version. Perhaps we could come up with a way to add some text with the link to the end of each Rmd? This should then would work for both versions.

**Comment by cansavvy** [comment]
Sounds like the most straightforward strategy. I can take a whack at this.

**Comment by cansavvy** [comment]
Zap's are on! Now just need a way to have this added to the Leanpub version.

**Comment by cansavvy** [comment]
The last bit to this issue is tracked here: https://github.com/jhudsl/leanbuild/issues/16 so it can be closed.
