### ISSUE TITLE
How do we update the 'mechanics' files in downstream repos when updates are made?

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#146]
# Summary 

I'd love to think we'd get this repo to a place where we'd never ever have to make fixes or updates again but that's just not reasonable. 

Is there a way we can ease the pain of carrying over "mechanics" updates to this template repo to all of its downstream children repositories? 

Basically we'd want these files to be updated occasionally: 

- getting_started.md 
- Some github workflow items in the .github folder (but not all)
- scripts/* folder
- docker/* folder
- assets/* folder
- code_of_conduct.md
- LICENSE 

But all other files in the downstream courses we don't want to upset as we make an update.

**Comment by cansavvy** [comment]
Like if we can do these kinds of steps: https://medium.com/sweetmeat/how-to-keep-a-downstream-git-repository-current-with-upstream-repository-changes-10b76fad6d97

But have protected files so that content or other repo specific changes aren't lost.

**Comment by cansavvy** [comment]
I looked into submodules: https://gist.github.com/gitaarik/8735255 Although its a nice thing to know, I do not think this will help make this process more user friendly so :-1:

**Comment by cansavvy** [comment]
I think this is what we want: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

BUT, I need to figure out how to make sure that when the template is used that this syncing github workflow itself isn't copied over because that would create chaos.

**Comment by cansavvy** [comment]
A person on this discussion has a solution for this problem: https://github.community/t/can-you-ignore-files-folders-when-making-a-repo-from-a-template/3279/7

Here's the GHA that is at the core of the solution: https://github.com/JetBrains/intellij-platform-plugin-template/blob/deb171483598ee8a5d7621154db880e87b4db4ef/.github/workflows/template-cleanup.yml

**Comment by cansavvy** [comment]
So close. The only thing that's in the way now is that the workflow can't run in the new repo without a GITHUB PAT being set so it just fails automatically: https://github.com/cansavvy/testing-template-cleaner-2/runs/3434001382?check_suite_focus=true

 I wonder if there's a way for it to extract/send the GITHUB PAT from this repo to do the authentication?

**Comment by cansavvy** [comment]
Going to look into this solution: https://gist.github.com/moltar/afe0e541ac87ed07f1454520683140de

**Comment by cansavvy** [comment]
Nope^ That wasn't exactly what we needed. Setting organization secrets though would be handy: https://github.blog/2020-05-22-keep-your-secrets-synced-across-multiple-repositories-with-organization-secrets/

**Comment by agitter** [comment]
> The only thing that's in the way now is that the workflow can't run in the new repo without a GITHUB PAT being set so it just fails automatically

Is this regarding the `starting-template.yml` workflow?  Because that push is to the same repository running the workflow, can you use the `secrets.GITHUB_TOKEN` instead of the `secrets.GH_PAT` here?
https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/fbcd1e3292bba57c7a9b2ef303a8d459904dcad9/.github/workflows/starting-course.yml#L71

It looks like that `secrets.GITHUB_TOKEN` token exists and has contents write permissions when the workflow first runs
https://github.com/cansavvy/testing-template-cleaner-2/runs/3434001382?check_suite_focus=true#step:1:16

**Comment by cansavvy** [comment]
Nice to hear from you, @agitter!

> Is this regarding the `starting-template.yml` workflow? 

Yes!

> Because that push is to the same repository running the workflow. 

Yes, this is ran by the "child" repository which does not have github token set when you first create it though the "parent" repository (this one) does. (However I think I can get around this by using an organization secret -- have not tested this yet but am about to). 

> Because that push is to the same repository running the workflow, can you use the `secrets.GITHUB_TOKEN` instead of the `secrets.GH_PAT` here?

I switched over the name of the token because the [syncing workflow github action](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/fbcd1e3292bba57c7a9b2ef303a8d459904dcad9/.github/workflows/downstream-mechanics-updates.yml#L16) required that the token be named `GH_PAT` per their documentation: https://github.com/marketplace/actions/repo-file-sync-action#-usage 

So I did some shuffling of the tokens to accommodate. 
> 
> It looks like that `secrets.GITHUB_TOKEN` token exists and has contents write permissions when the workflow first runs
> https://github.com/cansavvy/testing-template-cleaner-2/runs/3434001382?check_suite_focus=true#step:1:16

I'm going to make sure my secrets are all in a row and re-test. I was in the middle of working on this today but then had a meeting so I didn't finish it yet.

**Comment by agitter** [comment]
Got it.  I was hoping you would be able to continue using the personal access token for the syncing workflow and only switch to the  `GITHUB_TOKEN` secret for the template cleanup workflow because the [push action](https://github.com/ad-m/github-push-action#inputs) accepts either.  However, it sounds like you're a couple steps ahead of me with the token juggling.

**Comment by cansavvy** [comment]
Everything is working very nicely! I tested it out by making a new repo with the template. I unfortunately already deleted the repository I used as a test so I can't link to the final results but what's in main works! 

The one caveat is that if someone outside our organization uses the template, start-course.yml will fail until they set `GH_PAT`.

**Comment by cansavvy** [comment]
I also updated the documentation so this issue is done!
