### ISSUE TITLE
Docker image may not be handling Rstudio called python correctly

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#150]
In the current docker image and in the RStudio console, I tried to render [this repo's material](https://github.com/jhudsl/ITCR_Cancer_Research_Leadership_LeanPub) with `bookdown::render_book("index.Rmd")` and it contains some python in a knitr chunk.
https://github.com/jhudsl/ITCR_Cancer_Research_Leadership_LeanPub/blob/470671de8858804a3b807291cc54051df288e730/06-management_tools.Rmd#L306

I got this error: 
```
running: python  -c '# Now we are going to show some python code
x = [1,2,3,4,5]
print(x)'
Quitting from lines 300-303 (06-management_tools.Rmd) 
Error in system2(cmd, code, stdout = TRUE, stderr = TRUE, env = options$engine.env) : 
  error in running command
Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>

Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile 06-management_tools.Rmd
```

I'll look into this more later. I assume this runs fine locally for you, @carriewright11 ?

**Comment by carriewright11** [comment]
Yeah, the code works locally... I have some failures with docker image build but I don't think that is related, but maybe... still need to try with your updates to leanbuild for that repo.

**Comment by carriewright11** [comment]
looking into this some more...

**Comment by cansavvy** [comment]
Sounds like its time to address this.

**Comment by cansavvy** [comment]
> Yeah, the code works locally... I have some failures with docker image build but I don't think that is related, but maybe... still need to try with your updates to leanbuild for that repo.

@carriewright11 Could you send me a print out of your local `devtools::session_info()`  for your local machine? This may help me narrow in on the problem.

**Comment by carriewright11** [comment]
![Screen Shot 2021-09-16 at 9 15 14 AM](https://user-images.githubusercontent.com/23014755/133618912-a236d27f-c387-4a49-8631-ad7906165ff2.png)
![Screen Shot 2021-09-16 at 9 15 29 AM](https://user-images.githubusercontent.com/23014755/133618945-e88382c9-1060-4a1f-9a2e-09a9093799ed.png)

**Comment by cansavvy** [comment]
This is the problem: https://rstudio.github.io/reticulate/articles/r_markdown.html
When I run `Sys.which("python")` I get `""` which means it's not linked up to the python on the docker image.

**Comment by cansavvy** [comment]
I think this should be a simple fix if it works for you, if you get rid of the `python.reticulate = FALSE` tag it seems to run fine for me on the docker image. We can add this to the getting_started.md

**Comment by cansavvy** [comment]
@carriewright11 (forgot to tag you)

**Comment by carriewright11** [comment]
OK cool, I will give that a shot

**Comment by cansavvy** [comment]
This has been resolved! I added `reticulate` to the docker image #198 and now as long as the `python.reticulate = FALSE` tag is not used, python chunks appear to run properly: https://github.com/jhudsl/ITCR_Cancer_Research_Leadership/pull/60

**Comment by carriewright11** [comment]
yay :)
