### ISSUE TITLE
Figure out a way to hide TOC for coursera - maybe a version of the url?

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#156]
This would be better so that students don't get lost on coursera and to show the course with full width.

**Comment by carriewright11** [comment]
might be helpful: https://bookdown.org/yihui/bookdown/html.html I have considered just rendering in another format...

**Comment by carriewright11** [comment]
Alternatively we make a repo that copies bookdown files with git actions and renders to a version without the toc. (just don't copy the _output.yml file). Could also make this repo private with the coursera quiz code?

**Comment by carriewright11** [comment]
ooh or actually we could do this in the Leanpub repo. - rename to the course repo or something... because it would be easier to change the quizzes from leanpub to coursera all in the same repo.

**Comment by cansavvy** [comment]
That makes sense. What link do you provide coursera? If I can play around with that link perhaps I can figure out how to make the TOC disappear.

**Comment by carriewright11** [comment]
Sounds good - that would work too if you can make that happen! We would also host the current leanpub repo on GitHub pages. I think its ok to do that if it's private...(maybe we would need to pay... don't know but I could test it)

**Comment by carriewright11** [comment]
speaking of which... I think I need to make my Leanpub repo for my course private now!

**Comment by carriewright11** [comment]
> Sounds good - that would work too if you can make that happen! We would also host the current leanpub repo on GitHub pages. I think its ok to do that if it's private...(maybe we would need to pay... don't know but I could test it)

Just tested and you can have a public website from a private repo

**Comment by carriewright11** [comment]
> That makes sense. What link do you provide coursera? If I can play around with that link perhaps I can figure out how to make the TOC disappear.

oh sorry. I missed your question about the link: https://jhudatascience.org/ITCR_Cancer_Research_Leadership/

**Comment by cansavvy** [comment]
> oh sorry. I missed your question about the link: https://jhudatascience.org/ITCR_Cancer_Research_Leadership/

Is that all that coursera asks for then?

**Comment by carriewright11** [comment]
yup! just many times over lol with more specific links for each location like: https://jhudatascience.org/ITCR_Cancer_Research_Leadership/about-the-authors.html

**Comment by carriewright11** [comment]
One benefit of rendering in the leanpub repo is we could modify the style further if we wanted to - like keep the feedback button but remove the TOC for example

**Comment by carriewright11** [comment]
> That makes sense. What link do you provide coursera? If I can play around with that link perhaps I can figure out how to make the TOC disappear.

apparently if you press the s key it toggles the toc - that seems like a very useful clue

**Comment by cansavvy** [comment]
Wow. We opened a zillion issues about this. Lol This is resolved! #177

**Comment by carriewright11** [comment]
> Wow. We opened a zillion issues about this. Lol This is resolved! #177

lol
