### ISSUE TITLE
Be more prescriptive/restrict how we recommend people use links

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#160]
We need to tie up this leanbuild madness. So I'm working on chopping down the examples and showing clearly what works. 

If people need functionality beyond the few examples we show then they can file an issue and we can look to adding it to leanbuild if necessary. But I think we've gotten a bit side tracked with all the different use cases. Let's be very prescriptive about how to add things and if it doesn't work we can reevaluate. 

So toward this goal, I'm trying to make this template's examples more easy to follow and tightened up #159 

Then the more complicated test cases in 03-test-cases.Rmd can be made into a more formal test on the leanbuild package: 
https://github.com/jhudsl/leanbuild/issues/17

**Comment by carriewright11** [comment]
Yeah, that's why my plan was to drop html examples and only show include_slide() for images, include_url() for embed files and include_url() (but differently) for videos. Does that work for you?

**Comment by cansavvy** [comment]
I think we can consider this closed now that the examples are cut down and streamlined a bit.
