### ISSUE TITLE
Future idea: CourseraBuild package

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#166]
Enough people use Coursera too that if we create a bookdown -> coursera converting package that could also be useful. Not sure all what entails in Cousera but I'm just jotting this down incase we get enough stuff that it makes sense to have it be its own package. 

> This is great! Thanks for incorporating things! Maybe at some point we can incorporate this into package somewhere. Not sure it fits in with leanbuild since its for Coursera, but maybe a spinoff package like a "courserabuild" or something.

_Originally posted by @cansavvy in https://github.com/jhudsl/DaSL_Course_Template_Leanpub/issues/49#issuecomment-908503539_

**Comment by cansavvy** [comment]
Because some of the coursera machinery is currently split on both repositories (_Bookdown and _Leanpub) this might be a good argument for just making it its own package we can install on the docker image which can be used by both repositories. 

This way, the quizzes remain private on _Leanpub but the github pages only has to be in one place. 

What do you think, @carriewright11 ? For now, let's leave those coursera scripts split but then I can work on making them into a package.

**Comment by carriewright11** [comment]
I think this works for now, but it still might be a bit confusing if someone tries to use the coursera package to make quizzes from the bookdown repo. Hopefully though I can figure out something nifty with the json plugin and then that will not be an issue. We will see!

**Comment by cansavvy** [comment]
If they only have the bookdown repo then they won't be needing a Leanpub -> Coursera quiz converter anyway. In that case they would just make quizzes however you make quizzes for Coursera.

**Comment by carriewright11** [comment]
Oh I see you  are thinking for people that might only want to publish on coursera and not leanpub. Sure, that makes sense. Just wondering what our overall plan for the ITCR courses would be though -I think we might be required to do leanpub at least because it can be free and coursera can't. But I see your point for people in general.

**Comment by cansavvy** [comment]
I don't think this is totally needed anymore. I think incorporating into leanbuild worked fine.
