### ISSUE TITLE
Determine standard contribution labels

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#188]
We want to make sure everyone is given credit for what part they played in the courses. We need to flesh out what these labels would be. 

ultimately we need to have a table that lays out specifically what contribution label means like. Something like: https://www.cell.com/pb/assets/raw/shared/guidelines/CRediT-taxonomy.pdf but for courses.

e.g. author, contributor, administration, concept generation, idea person, etc

**Comment by cansavvy** [comment]
Once the labels are determined, I will add these to the About.Rmd template so they are easy to fill in. Also probably add a blurb in getting_started.md

**Comment by cansavvy** [comment]
Sounds like this is mostly wrapped up.

**Comment by carriewright11** [comment]
Let me know if you want help with implementing this.
