### ISSUE TITLE
Determine how to add credits to Leanpub version of course

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#219]
Related to https://github.com/jhudsl/DaSL_Course_Template_Bookdown/issues/188, that markdown table will likely not work for the Leanpub version or at the very least it will needed to be added to the About the course section of Leanpub -- or it needs to be determined where it will go.

**Comment by cansavvy** [comment]
@carriewright11 Is this something you'd want to figure out?

**Comment by carriewright11** [comment]
Sure! I have been thinking about this... wondering if making a shiny app that would allow people to fill out different roles would be good. Obviously that would take some time... but I have something I could maybe build on that would at least make it a tad easier. Also, trying to think about simpler solutions.

**Comment by cansavvy** [comment]
I think there’s a lot of instances where a Shiny app would be great for the template, but obviously I think we have bigger fish to fry before we can get to that.

**Comment by carriewright11** [comment]
I think we can close this now.
