### ISSUE TITLE
problem: citations are not rendering correctly

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#225]
**Describe what is not working with the template or is unclear in the documentation**

Locally I see references for each chapter (and the end), now only see them at the end when the book is rendered with the git action instead of locally.

https://jhudatascience.org/ITCR_Cancer_Research_Leadership/index.html

**Please link to the specific course repository you are working on**

https://github.com/jhudsl/ITCR_Cancer_Research_Leadership 

**To Reproduce**
1. Go to https://github.com/jhudsl/ITCR_Cancer_Research_Leadership 
2. create a pull request to trigger the build and push workflow
3. go to the new version of the course at https://jhudatascience.org/ITCR_Cancer_Research_Leadership/index.html
4. See how the references are not at the end of the chapters
for example here:
https://jhudatascience.org/ITCR_Cancer_Research_Leadership/guidelines-for-multidisciplinary-informatics-teams.html#conclusion

**Expected behavior**
Expected to see references for each chapter. This is the way the references look when the book previews locally.

**Github actions links**
If applicable please link to the Github actions that has failed
https://github.com/jhudsl/ITCR_Cancer_Research_Leadership/actions/runs/1258079636/workflow
Did not fail... but from this GitHub action

**Screenshots**

**Additional context**

**Comment by cansavvy** [comment]
This is great! :tada: Thanks so much for filling it out!

**Comment by cansavvy** [comment]
@carriewright11 
> Expected to see references for each chapter. This is the way the references look when the book previews locally.

I'm trying to replicate this notion^, and locally for me (using the `main` branch) I don't get chapters at the end of each reference. For me, on the `jhudsl/course_template` docker image, whether I run by 
```
          docker run \
          --mount type=bind,target=/home/rstudio,source=$PWD \
          jhudsl/course_template \
          Rscript -e "bookdown::render_book('index.Rmd')"
``` 
Or if I go on the docker image, localhost:8787 and I run `bookdown::serve_book()` I get the same output. 

So as far as inconsistency between the serve_book() and github actions, I can't see any. 

But, my follow up question: Do we want the references at the end of each chapter? How strong is this preference? I can work on it if we have a strong preference for it. (I personally don't have a strong preference either way).

**Comment by carriewright11** [comment]
I personally think it is easy for readers, because otherwise it moves them out of the chapter when they click on a link, but we can talk to Jeff about this at the meeting tomorrow. I thought I remembered seeing them in your course at some point at the end of each chapter as well but I don't know :P. 

I guess the inconsistency must have something to do with my local set up. Will think about this more...

**Comment by carriewright11** [comment]
OK just checked your course on Leanpub and indeed you also have them at the end of each chapter. It seems like there might be something different about the Docker image that might account for this?

**Comment by cansavvy** [comment]
> It seems like there might be something different about the Docker image that might account for this? 

Is this a problem you are only encountering on https://github.com/jhudsl/ITCR_Cancer_Research_Leadership ?  (I'm not encountering it on Documentation_and_Usablity as you mentioned. Just wondering if any of the css or style things or some other setting on https://github.com/jhudsl/ITCR_Cancer_Research_Leadership might disrupted this? Would be good to know what it is so we can warn people.

**Comment by carriewright11** [comment]
Yes, I do see that although your Leanpub version has references, (which is probably from a previous version I would imagine?) this version doesn't seem to: https://jhudatascience.org/ITCR_Documentation_and_Usability/.  I will keep looking into what might have changed recently.

**Comment by carriewright11** [comment]
I will try with another repo as well

**Comment by carriewright11** [comment]
![Screen Shot 2021-09-23 at 1 22 00 PM](https://user-images.githubusercontent.com/23014755/134554725-943bbd7c-61bf-48e9-9356-12da6be17337.png)
![Screen Shot 2021-09-23 at 1 22 13 PM](https://user-images.githubusercontent.com/23014755/134554778-6c026e42-9165-4680-bfb7-d5c3115b336e.png)
)

**Comment by carriewright11** [comment]
![Screen Shot 2021-09-23 at 1 22 00 PM](https://user-images.githubusercontent.com/23014755/134554725-943bbd7c-61bf-48e9-9356-12da6be17337.png

**Comment by carriewright11** [comment]
2.11.4

**Comment by cansavvy** [comment]
Leanpub versions have citations at the end of each chapter while bookdown does not. Its not a version problem, we've narrowed that down. I also saw if maybe its a `--citeproc` difference, it is not. 

I believe leanbuild makes the references using this: https://github.com/jhudsl/leanbuild/blob/03f75bceb187511416fd9f1426a4f171e8f28ebe/R/bookdown_to_leanpub.R#L268

So we could add this to the GHA render step

**Comment by cansavvy** [comment]
Right now I think the biggest suspct is bookdown: 0.20 on the docker image, but 0.24 for @carriewright11 's local computer. So I'm going to bump up to .24 and see what happens.

**Comment by carriewright11** [comment]
https://bookdown.org/yihui/bookdown/citations.html - If you read the last part of this it suggest that it has to do with how the output style is specified.

**Comment by carriewright11** [comment]
https://pandoc.org/MANUAL.html#placement-of-the-bibliography

**Comment by carriewright11** [comment]
perhaps an alternative, is that we can link to the actual source instead of the reference list: https://pandoc.org/MANUAL.html#other-relevant-metadata-fields

Still better to probably have the original option though... hope the bookdown version change works!!

**Comment by cansavvy** [comment]
Upgrading bookdown to 0.24 fixed it! https://jhudatascience.org/DaSL_Course_Template_Bookdown/topic-of-section.html

**Comment by cansavvy** [comment]
I've also deleted the references.Rmd file and updated _bookdown.yml accordingly!

**Comment by carriewright11** [comment]
> I've also deleted the references.Rmd file and updated _bookdown.yml accordingly!

Does this not result in the references being appended to the about page like it was? or you also modified that?

**Comment by carriewright11** [comment]
> > I've also deleted the references.Rmd file and updated _bookdown.yml accordingly!
> 
> Does this not result in the references being appended to the about page like it was? or you also modified that?

Looks like they are at the bottom after session info.
I am ok with having references in both places if you are.
