### ISSUE TITLE
What is the roadmap / policy for upgrading to R-4.1.1?

### ISSUE THREAD

**Issue by cutsort** [jhudsl/OTTR_Template#232]
- Worth adding tools like vi(m) less etc. to the Dockerfile?
- What is the roadmap / policy for upgrading to R-4.1.1?  Current R-4.0.2 locks us into Bioconductor 3.12 (Oct 2020)

**Comment by cansavvy** [comment]
`vim` has been added to the docker image. Now this is left with a question of how/when do we update to R 4.1.1

**Comment by cutsort** [comment]
vim users rejoice :)

Possible to maintain two versions?  This would allow us to support the current and prior Bioconductor release ...

**Comment by cansavvy** [comment]
> Possible to maintain two versions? This would allow us to support the current and prior Bioconductor release ...

Possible: yes. Ideal? No. 

Is there a particular need that upgrading Bioconductor is helping address? Maybe this will help me understand the pros and cons, because right now I only see cons.
