### ISSUE TITLE
> Re-rendered previews from the latest commit:

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#245]
> Re-rendered previews from the latest commit:
> 
> * See [preview of Bookdown here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/jhudsl/DaSL_Course_Template_Bookdown/preview/docs/index.html)
> * See [preview of Coursera version here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/jhudsl/DaSL_Course_Template_Bookdown/preview/docs/coursera/index.html)
> 

These don't appear to have my current changes. :(
> _Updated at 2021-09-24 16:08:44_

These don't seem to have my current edits :(

_Originally posted by @carriewright11 in https://github.com/jhudsl/DaSL_Course_Template_Bookdown/issues/244#issuecomment-926755442_

**Comment by cansavvy** [comment]
Closing in favor of issue description on #247 Will track over there.
