### ISSUE TITLE
references.Rmd as well as refs at end of chapters?

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#246]
> > I've also deleted the references.Rmd file and updated _bookdown.yml accordingly!
> 
> Does this not result in the references being appended to the about page like it was? or you also modified that?

Looks like they are at the bottom after session info.
I am ok with having references in both places if you are.

_Originally posted by @carriewright11 in https://github.com/jhudsl/DaSL_Course_Template_Bookdown/issues/225#issuecomment-926752618_

**Comment by cansavvy** [comment]
Both places is fine

**Comment by carriewright11** [comment]
OK I can add this back

**Comment by cansavvy** [comment]
Looks like this was done in #241
