### ISSUE TITLE
Add reminder to publish to Leanpub issue

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#257]
Adding a reminder to publish issue for when changes to Leanpub `manuscript` happen. 

I thought adding this reminder issue for publishing to Leanpub would be a nice quick add before 1.0, but it is failing: https://github.com/jhudsl/DaSL_Course_Template_Leanpub/actions/runs/1282527944

Because its not a high priority, I reverted it for now and I'll return to it later.

**Comment by carriewright11** [comment]
I like this!

**Comment by cansavvy** [comment]
We may not need this if iframes work on Leanpub

**Comment by carriewright11** [comment]
good point - and/or if they improve the integration with their API

**Comment by cansavvy** [comment]
This is not an issue now that iframes work!
