### ISSUE TITLE
For feedback, send email to thank people

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#291]
**Is your feature request related to a problem? Please describe.**
I've gotten some feedback on the Docs and Usability course quizzes. 

It was super nice of them to alert me to a few bugs. 

We should have an automatic email sent to people as they give us feedback. 

**Describe the solution you'd like**
Should be able to use Zapier for this.

**Comment by cansavvy** [comment]
We could use itcrtrainingnetwork@gmail.com for this?

However now I'm debating about whether it makes sense to automate this. Some people may not provide their email which might make this break. 

But a confirmation of sorts that their feedback has been received is probably necessary. I think Google Forms has something built in? I'll check.

**Comment by carriewright11** [comment]
> **Is your feature request related to a problem? Please describe.** I've gotten some feedback on the Docs and Usability course quizzes.
> 
> It was super nice of them to alert me to a few bugs.
> 
> We should have an automatic email sent to people as they give us feedback.
> 
> **Describe the solution you'd like** Should be able to use Zapier for this.

aww nice idea :)

**Comment by avahoffman** [comment]
What about this option for google forms?
![image](https://user-images.githubusercontent.com/15618412/153457419-0b3b2132-c9ee-4b73-9e24-53819e5c963e.png)

**Comment by cansavvy** [comment]
Yes! That should work!

**Comment by cansavvy** [comment]
Done!
