### ISSUE TITLE
Update License

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/OTTR_Template#296]
The template currently has an [MIT License](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/main/LICENSE), which gets propagated to courses.  Courses generally want to be licensed under CC-BY.

On Basecamp we discussed changing the license for the template to CC-BY to make things easy for courses.

Other option, if we want to keep the template on MIT, would be to add some information in the wiki about changing your course's license as part of repository set up (might be a good idea to add that anyway).

**Comment by cansavvy** [comment]
I'm fine with changing to CC-BY, I think this makes sense, Do you want to file a PR for this, @KatherineCox ?

**Comment by KatherineCox** [comment]
~~Happy to file a PR, not quite sure how to set up the license.  Looks like CC-BY isn't available as one of the license types provided through GitHub.  Looking at the CC website, I didn't find an official plaintext or markdown version (and they encourage you just to link to their site).~~

~~I can~~

~~a) delete the LICENSE file and just add the link in the README~~

~~b) Add the link to the LICENSE file (without the text of the license), e.g.:~~

> <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

~~c) `usethis` has a plaintext version we could use, if we want to include a copy of the text in the LICENSE file~~

~~Thoughts?~~

Nevermind, found plaintext versions, they were just well hidden :) https://creativecommons.org/2014/01/07/plaintext-versions-of-creative-commons-4-0-licenses/

I'll submit a PR in a bit

**Comment by KatherineCox** [comment]
Ah, @cansavvy, another question - the link that's currently at the bottom of the readme is for CC-BY 3.0.  Is there a reason for using 3.0, or should we go with 4.0?

**Comment by cansavvy** [comment]
> Ah, @cansavvy, another question - the link that's currently at the bottom of the readme is for CC-BY 3.0. Is there a reason for using 3.0, or should we go with 4.0?

I'm not aware of a reason. But also don't know the differences between the versions!

**Comment by KatherineCox** [comment]
Looks like the link in the bottom of the README is for 3.0 but the link in the footer of the rendered book is for 4.0, so we're a bit confused about things anyway :)

I don't know the details of what's different, just that the updates in 4.0 are generally about clarifying some things that were confusing or ambiguous about 3.0.  I'm going to go ahead and switch the README and repo license to 4.0 to match the rendered book, unless you think I should check with Ira.

**Comment by carriewright11** [comment]
I think having different versions was just an error. Thanks @KatherineCox!
