### ISSUE TITLE
What should be included in the READMEs for the courses? (Template READMEs)

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#3]
### Background 

I was browsing the course repos made from this template so far and was hoping to see a link to the rendered version or the LeanPub in the README: https://github.com/jhudsl/ITCR_Cancer_Research_Leadership/blob/main/README.md 

### Idea/Thing to discuss:
What basic items a course README should have? Before the template is used and multiplied a bunch of times it would probably be good to have a well established README template. 

This README template might include info like: 

- Link to rendered bookdown and probably the leanpub.
- Perhaps a link to the ITCR training website and some context about why the course exists.
- Links to any relevant slides? (Perhaps these don't exist yet). 
- Info for people who would like to contribute to the course material (where do they go -- how should they get started?)

There may be other things that I haven't listed here that would be helpful to have in all course READMEs. 

### Additional issue: 
We'll need the README for the template to be different than the template README for the courses -- what's the least clunky way to do this? Could just include a template section in the current README and indicate that the rest of the instructions should be deleted after the template is used.

**Comment by cansavvy** [comment]
> We'll need the README for the template to be different than the template README for the courses -- what's the least clunky way to do this?

Thinking a bit more about this^ I think it makes sense to put that information in a `CONTRIBUTING.md` document that will instruct individuals on everything they need to know to contribute content.

**Comment by carriewright11** [comment]
all sounds good to me
