### ISSUE TITLE
Delete old .md and .html files from /docs

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/OTTR_Template#318]
**Describe what is not working with the template or is unclear in the documentation**
When .Rmds are deleted, the corresponding .md and .html files in `/docs` are not deleted.  This means that pages like [this](https://jhudatascience.org/GDSCN_Book_SARS_Galaxy_on_AnVIL/topic-of-section) exist in the rendered book.

**Please link to the specific course repository you are working on**
https://github.com/jhudsl/GDSCN_Book_SARS_Galaxy_on_AnVIL
(also a problem for our other AnVIL guides, but this is the most recent and likely has the most up-to-date version of the template)

**To Reproduce**
1. Set up repository using template
1. Delete e.g. `02-chapter_of_course.Rmd`, and merge/rerender site
1. Visit the url for the deleted content e.g. \(course-url\)`/topic-of-section`

**Expected behavior**
Sections that no longer exist in the .Rmd source files don't exist in the rendered output.

**Comment by cansavvy** [comment]
It just so happens I already have this change in the works! Its related to #317 and I'll be filing a PR shortly. Thanks for the issue. Let me know if you see anything else!

**Comment by KatherineCox** [comment]
@cansavvy that will take care of the lingering example files, but I think the problem will still exists if I create a new Rmd and then later decide I don't want that section.

e.g https://jhudatascience.org/AnVIL_Book_Getting_Started/student-account-setup.html shouldn't exist anymore, since we removed it from the .Rmd content

**Comment by KatherineCox** [comment]
I think we need a way to delete the content of docs every time the book rerenders.

**Comment by cansavvy** [comment]
Yeah, this has been on my TODO list: See #111 

If you'd like to take a whack at it, that'd be great, but I can also bump it up on my priority list.
