### ISSUE TITLE
Issues that should automatically be filed with a new course?

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#32]
We can make it so when you use this template, issues that you can follow along to set up the course are automatically filed. We should think about what these are and how this might work in conjunction with the BaseCamp course template.

**Comment by KatherineCox** [comment]
It would be nice to have a list of the template files that needed editing (and any corresponding instructions or style guides).  I'm finding

- README.md
- index.Rmd
- About.Rmd
- _bookdown.yml
- `01-intro.Rmd`
- `02-chapter_of_course.Rmd`
- book.bib - we should leave the existing references, correct?
- packages.bib - we should leave the existing references, correct?
- I don't know what ITCR_Course_Name.rds is, or whether I should do anything with it

**Comment by cansavvy** [comment]
@KatherineCox This is a great idea! We can definitely set up issues to guide people to what needs to be edited!

**Comment by cansavvy** [comment]
This isn't working. Need to look into the error.

**Comment by cansavvy** [comment]
This works now and is documented!
