### ISSUE TITLE
Feedback button

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#322]
Sounds like people are interested in feedback button feature. Should at least add an explanation of how to do this to the wiki but it would be great to actually have an automatic option. Fred suggested automatically linking to creating issues for the respective repo.

**Comment by carriewright11** [comment]
I suggested that we could make more project specific style docs that could be used for more projects like we did for DataTrail. Still might be something to think about in general.

**Comment by cansavvy** [comment]
We've come up with genera plan on BaseCamp for incorporating the feedback button.

The default will be that the feedback button goes to the "https://github.com/<repo>/issues"

It's a good idea for to have authors explicitly choose a feedback method. So we'll have an autogenerated issue upon using the template that says to pick a feedback method. 

We'll also need to explain and link to the wiki about how to give and use a feedback method.

**Comment by cansavvy** [comment]
Being addressed on #326
