### ISSUE TITLE
These two chapters between two courses are almost identical - issue

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#339]
## Is your feature request related to a problem? Please describe.

There's some courses that might be borrowing content from each other. We don't want to just copy and paste because this can make a maintenance nightmare. If the files are *exactly* alike we could use the sync GHA, but with slide IDs and chapter numbers its unlikely this would be the case. 

## Describe the solution you'd like

One strategy is just to link from one to the other, but another strategy would be to set up a GitHub action to remind an author to take a look at a file's twin should they file changes to a file that has a twin. 

Not sure how much this is something we need -- may end up just making things more complicated

**Comment by cansavvy** [comment]
It's well on its way to being solved. https://github.com/jhudsl/cow/pull/13 Just needs to be documented and added to the docker image.

**Comment by cansavvy** [comment]
This is still in progress on #354. It's mostly there, just adding documentation

**Comment by carriewright11** [comment]
this is done now right @cansavvy ?

**Comment by cansavvy** [comment]
Yes!
