### ISSUE TITLE
Rename contributing to getting started and add "contributor code of conduct"

### ISSUE THREAD

**Issue by jtleek** [jhudsl/OTTR_Template#34]
@cansavvy can we rename the contributing.md to "getting started" and then add a contributor code of conduct?

**Comment by cansavvy** [comment]
Sounds good! Do you have an example/ideas of what should be included in the contributor code of conduct?

**Comment by cansavvy** [comment]
The one downside to changing the name of `CONTRIBUTING.md` is that Github does have automatic prompts to people when CONTRIBUTING.md changes or if they have not looked at it. 

In regards to code of conduct Here's an example: https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.md

It almost should be its own file that we link to in `getting_started.md` perhaps?

**Comment by jtleek** [comment]
Yeah that is a downside :(. On the other hand I was just about to write
a message asking for a getting started guide because I couldn't find it,
then I realized that was the CONTRIBUTING.md .... I wonder if there is a
way we can just really bold the idea that the place to start is
contributing. I agree with the link out to a separate file for the code
of conduct!

On April 13, 2021, GitHub ***@***.***> wrote:
> The one downside to changing the name of CONTRIBUTING.md is that
> Github does have automatic prompts to people when CONTRIBUTING.md
> changes or if they have not looked at it.
>
> In regards to code of conduct Here's an example:
> <https://www.contributor-
> covenant.org/version/2/0/code_of_conduct/code_of_conduct.md>
>
> It almost should be its own file that we link to in getting_started.md
> perhaps?
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhudsl/ITCR_Course_Template_Bookdown/issues/34#issuecomment-
818686451>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAL7WWQJOWH5HCHNAT4VV4DTIQYL3ANCNFSM423GIBSA>.

**Comment by cansavvy** [comment]
Currently I have in the README: 

> If you would like to contribute to this course material, take a look at the CONTRIBUTING.md to get started and/or contact us on the ITCR training website.

But if we thinking changing it to `getting_started.md` is still clearer, I'm fine with that.

**Comment by jtleek** [comment]
I think it would be if thats ok

On April 13, 2021, GitHub ***@***.***> wrote:
> Currently I have in the README:
>
> > If you would like to contribute to this course material, take a look
> > at the CONTRIBUTING.md to get started and/or contact us on the ITCR
> > training website.
> >
>
> But if we thinking changing it to getting_started.md is still clearer,
> I'm fine with that.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhudsl/ITCR_Course_Template_Bookdown/issues/34#issuecomment-
818693576>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAL7WWUJSRUG4O2OTRLPI2TTIQZYHANCNFSM423GIBSA>.
