### ISSUE TITLE
Way of getting reminders of text updates if you borrow text from another course

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#354]
## Is your feature request related to a problem? Please describe.

We are starting to borrow text from other classes. We want to have a reminder to check the text that was borrowed if the original text gets modified. 

## Describe the solution you'd like

We could copy the rmd that the text comes from but not include it in the _bookdown.yml file - likely a different directory. When there are changes to the original rmd in its original repo - we could sync the file from that repo the way we currently do file syncs- saying "hey there have been changes to a file that you borrowed text from" then we can optionally pull those changes to the copied rmd file and easily see what the edits are to potentially (manually) add to the rmd that the borrowed text is in. 

## Describe alternatives you've considered

Not sure what the other alternatives are. We could just get a reminder to check borrowed text in general- which is easier to implement, but this would be more helpful.

**Comment by cansavvy** [comment]
Related to #339

**Comment by cansavvy** [comment]
I have a solution better than reminders and I'm using it to borrow from the Wiki of this repo for Intro_to_OTTR. I will write up some docs and maybe a formalized function for it. It will be super elegant and no manual changes needed. Edit once and it will appear in both!

**Comment by cansavvy** [comment]
https://github.com/jhudsl/cow/pull/13

**Comment by cansavvy** [comment]
This is in the Docker image now. I'm trying it out in the Advanced Reproducibility course here: https://github.com/jhudsl/Adv_Reproducibility_in_Cancer_Informatics/pull/23

Will add to the Wiki if this works.

**Comment by cansavvy** [comment]
This is documented and working!! https://github.com/jhudsl/OTTR_Template/wiki/Borrowing-chapters-between-courses Please let me know what questions you have. The `cow` package is incorporated into the docker image so if you use this on the docker image or through rendering by GitHub actions, it should work!
