### ISSUE TITLE
Figure out what parts of the template could be automagically set up 

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#359]
## Is your feature request related to a problem? Please describe.

Software Carpentries uses Jekyll to automatically set some text up. Could we do the same here? 

Or at the very least could we delete the README section not relevant to the individual courses? https://github.com/jhudsl/DaSL_Course_Template_Bookdown#dasl-course-templates

**Comment by carriewright11** [comment]
I like this one... what about incorporating some RStudio addins to leanbuild?

**Comment by cansavvy** [comment]
This is too general and too old of an issue to be useful. Closing now.
