### ISSUE TITLE
Create a link to download spell check results in the GHA bot rendered previews

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/OTTR_Template#364]
Maybe I'm just on the struggle bus but I feel like I'm always hunting around for the spell check output.. I was thinking it might be kind of nice to include a link to download the .tsv here:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/15618412/146558054-af479500-2d10-4274-bdbb-a55c6824b833.png">

low priority tho - just getting this idea out there

**Comment by cansavvy** [comment]
Excellent idea! I am happy to help on this!

**Comment by KatherineCox** [comment]
That would be great!

**Comment by cansavvy** [comment]
https://github.com/marketplace/actions/workflow-artifact-pull-request-comment 

This GitHub actions might be able to do it for us if we borrow from it.

**Comment by cansavvy** [comment]
Why stop here!? Might as well make one for the URL checker too.

**Comment by cansavvy** [comment]
It's working and its great: https://github.com/jhudsl/OTTR_Template/pull/371 Great idea!
