### ISSUE TITLE
outdated workflow name for file transfer from render workflow

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#367]
## Is your feature request related to a problem? Please describe.
The workflow name in transfer-rendered-files.yml to run after for the workflow dispatch is: [ "Build, Render, and Push" ], but I think it should be ["Render Bookdown and Coursera"]

## Describe the solution you'd like
Just need to update  transfer-rendered-files.yml.

**Comment by cansavvy** [comment]
This should be fixed now!
