### ISSUE TITLE
Style updates

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#375]
In reference to #365 I would like to:

-  describe more in the wiki about what is possible with the current style options

-  make some of these style elements more customizable (would be great if we could automate some of this at some point... I can imagine an rstudio [addin](http://rstudio.github.io/rstudioaddins/)) Addins could also be great for automating other aspects!

- clean up the style code a bit to remove anything we need/want

**Comment by cansavvy** [comment]
@carriewright11 I'm going to close this issue and we can reopen if we still think its pressing.

**Comment by carriewright11** [comment]
OK I might make a new issue about making style elements customizable and automated
