### ISSUE TITLE
["Problem"] previewing new chapters

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/OTTR_Template#378]
## Describe what is not working with the template or is unclear in the documentation
I haven't tested thoroughly, but I've noticed a couple times that the auto-generated preview has trouble with newly created chapters.

If I merge the PR, the new chapter renders fine and the links work in the "published" bookdown; it's just in the preview that it's broken.

## Please link to the specific course repository you are working on
https://github.com/jhudsl/AnVIL_Book_Getting_Started/pull/127

Here's an open PR demonstrating the problem.  I've added a new chapter at the end of the book (as Appendix H).  The link shows up in the toc, but it's broken (404 error).

I saw the same problem on [this PR](https://github.com/jhudsl/AnVIL_Book_Getting_Started/pull/123) (adding "Appendix B: Troubleshooting"), but now that I've merged it the chapter shows up as expected in the published book (and the preview is gone, so, you can't see the problem there).

## To Reproduce
1. Clone/pull repo and make branch
1. Add a new chapter (.Rmd file), also add it to _bookdown.yml.  This renders fine locally.
1. Push changes (.Rmd file, _bookdown.yml) and make a PR
1. View the autogenerated GitHub preview (Bookdown) and try to view the new chapter.  The new chapter shows up in the table of contents, but I get a 404 error if I try to click on it.

This repo has been synced with the OTTR_Template repo as of the most recent release, so the github actions should be up-to-date minus any changes made since then.

**Comment by cansavvy** [comment]
I'll take a look into this, @KatherineCox Thanks!
