### ISSUE TITLE
Documentation - Crosslinking?

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/OTTR_Template#379]
What's the best way to do cross-linking (e.g. between chapters)? Is there a way that plays nicely across platforms?  Or does cross-linking only work if I stick to Bookdown and don't try to port to Leanpub or Coursera?

**Comment by cansavvy** [comment]
By cross linking, do you mean providing a link to another chapter in a different chapter? 

If so, I generally put the full link aka something like: https://jhudatascience.org/Reproducibility_in_Cancer_Informatics/defining-reproducibility.html

This unfortunately doesn't work cross platform, but we can definitely implement something that does.

**Comment by KatherineCox** [comment]
Yeah, linking from one chapter to another.  In the AnVIL books, there are a lot of places where it's nice to be able to say "for more information on X, see `this chapter`".

**Comment by KatherineCox** [comment]
We're currently only using Bookdown, so, not an urgent request, just trying to figure out best practices and future-proof if we decide to put things on the other platforms.

**Comment by cansavvy** [comment]
This does work across platforms now that we have iframes! But we should document this.

**Comment by cansavvy** [comment]
Done: https://github.com/jhudsl/OTTR_Template/wiki/Borrowing-chapters-between-courses
