### ISSUE TITLE
Set permissions for syncs to non-jhudsl repos

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#384]
## Is your feature request related to a problem? 

https://github.com/jhudsl/OTTR_Template/actions/runs/1689833133

The sync pr GitHub action doesn’t work for non jhudsl repos because of lack of permission.

So we need to figure out how to set the permissions correctly for syncs 

Might be as simple as adding jhudsl or something as an external collaborator.

**Comment by carriewright11** [comment]
Happy to help test this out for OCS!

**Comment by cansavvy** [comment]
This is addressed by #389 and #387

**Comment by cansavvy** [comment]
I'll reopen if it breaks
