### ISSUE TITLE
Problem: Trouble building with jhudsl-robot

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/OTTR_Template#400]
I know this is bleeding edge, so, if some of this is still under construction, no worries, just documenting a couple problems I ran into using the template as of last Friday (1/14).

repository: https://github.com/jhudsl/GDSCN_bookdown_style

At first I tried setting it up without adding jhudsl-robot as a collaborator (since I'm part of jhudsl) but I was running into errors with `Commit rendered bookdown files`

```
remote: Permission to jhudsl/GDSCN_bookdown_style.git denied to jhudsl-robot.
fatal: unable to access 'https://github.com/jhudsl/GDSCN_bookdown_style/': The requested URL returned error: 403
```

Once I added jhudsl-robot, that error went away but I got a new one, also in `Commit rendered bookdown files`:

```
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To https://github.com/jhudsl/GDSCN_bookdown_style
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/jhudsl/GDSCN_bookdown_style'
No changes to push
```
My PR had an approving review, so I'm guessing it's something jhudsl-robot is doing that's triggering the branch protection rule?  Is there a setting I should tweak somewhere?

Here are some PRs with different attempts at getting it to work (with/without adding jhudsl-robot, and then with/without approving review)
https://github.com/jhudsl/GDSCN_bookdown_style/pulls?q=is%3Apr+is%3Aclosed

**Comment by cansavvy** [comment]
Ah! Thanks for bringing this up. @KatherineCox  I was doing some tests on Friday and forgot to restore some of `jhudsl-robot`'s privileges. I just did that now so this *may* be fixed. But it's also possible there are still outstanding problems. Let me know and I'll be keeping an eye out myself.

**Comment by cansavvy** [comment]
Sorry for the confusion! I think this was my fault because I forgot to restore things after the tests I ran.

**Comment by KatherineCox** [comment]
@cansavvy Hmmm, at the moment I'm still seeing the same "At least 1 approving review is required by reviewers with write access" error.

https://github.com/jhudsl/GDSCN_bookdown_style/pull/12

Do you know if your changes should work right away?  I can try again later today if it takes a little while to update.

Edit: I just double checked and confirmed that jhudsl-robot has write access to my repo.

**Comment by cansavvy** [comment]
@KatherineCox Working on this currently. Will try to push fixes as soon as possible

**Comment by KatherineCox** [comment]
Thanks! I'm still able to work on things locally, so this isn't a huge blocker for me yet.

**Comment by cansavvy** [comment]
This should all be resolved as far as I am aware, but @KatherineCox please let me know if it breaks again.

**Comment by KatherineCox** [comment]
It's working for me now, thanks!
