### ISSUE TITLE
[Documentation]: How to manually trigger workflows

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#401]
Write about how to trigger github actions manually in the wiki. 

Sometimes this can come in handy!

<img width="1182" alt="Screen Shot 2022-01-18 at 1 59 05 PM" src="https://user-images.githubusercontent.com/23458084/150001580-3c19d630-f388-4d34-aef5-92268ce8753e.png">

@KatherineCox This is probably pertinent to you based on what I noticed you were doing to force re-renders on https://github.com/jhudsl/GDSCN_bookdown_style

You can go to `Actions` > Choose the github action you'd like to trigger  like `Render Bookdown and Coursera` > Then go to `run workflow` > and click the green button that says `Run workflow`.

**Comment by KatherineCox** [comment]
Thanks!  I was wondering if there was an easier way to run the actions :)

**Comment by cansavvy** [comment]
Done! https://github.com/jhudsl/OTTR_Template/wiki/How-to-set-up-and-customize-GitHub-actions-robots#manually-running-rendering-or-checks
