### ISSUE TITLE
Set default template button to use a release and not main

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#408]
## Describe the your scope of your content idea

I want to be able to set the `use this template` button to by default use the latest release instead of what’s in main. Sometimes the things in main don’t quite pan out so I’d hate for someone to create a new course with something less tested. But the releases are at a higher confidence level than what is in main at any particular moment.

I’m just not sure how to do this or if it’s an available option in GitHub.

**Comment by cansavvy** [comment]
I think the easiest way to do this is to have a `dev` or `staging` branch that we introduce changes to. Then only upon a new release are the changes actually put into `main` for users to use.

**Comment by cansavvy** [comment]
Only problem with this solution is that you can't set one branch to the default PR branch and a different branch to the one for the default to be used as the template. So we'd have to manually always make our PRs to `staging` if we do this.

**Comment by cansavvy** [comment]
So, the riskier changes the plan is now to send them to `staging` if possible. That's as good as we can do for this for now.

**Comment by KatherineCox** [comment]
@cansavvy This would also be resolved if we go with the "meta template" approach, right?

Like, if I set up a "AnVIL_Template" (which syncs with OTTR_Template), and I use the "AnVIL_Template" as the base for all my courses, then it should always be at a stable state, since it will only receive updates when they're released from the OTTR_Template.

**Comment by cansavvy** [comment]
Sort of. Though I expect some (like myself) will still use the main OTTR Template for courses
