### ISSUE TITLE
Make it so _Quizzes repositories are optional 

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#417]
If course creators don't care about quizzes being private then they should be able have quizzes and connect this repository to Leanpub. 

This would make a lot of things simpler so that someone can have just one repository if they want.

**Comment by cansavvy** [comment]
YAY! This was very easy to do. Now to document it all!

**Comment by cansavvy** [comment]
This was remarkably easy to do! (Hopefully it continues working well) 

See the documentation updates on https://github.com/jhudsl/OTTR_Template/wiki/Publishing-on-Leanpub

**Comment by cansavvy** [comment]
@tmm211 The one repository option is now the default (so no need to use the _Quizzes repository) 

If you want to try it out and tell me what you think, I would love any feedback you have. See updated docs here: https://github.com/jhudsl/OTTR_Template/wiki/Publishing-on-Leanpub

**Comment by tmm211** [comment]
No way! Exciting!! I will try it out!
________
Tiffany Miller (she/her)
Data Sciences Platform
<https://www.broadinstitute.org/data-sciences-platform>
Broad Institute of MIT and Harvard

**Comment by cansavvy** [comment]
This is done for now (unless/until we encounter any problems with it).
