### ISSUE TITLE
Start up Google Group for OTTR Users

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#429]
Don't really know what entails in this but @avahoffman brought it up as a good way for people to be updated about OTTR and for them to report their own problems. 

It's like a forum of sorts. 

I'm opening this issue for us to keep track of the formation of the Google Group but also remember to document it in the Wiki.

**Comment by avahoffman** [comment]
I think this is resolved by https://github.com/jhudsl/OTTR_Template/wiki/Getting-Help-(Google-Group)

**Comment by cansavvy** [comment]
Done!
