### ISSUE TITLE
make bs4 book theme available

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/OTTR_Template#44]
On Basecamp we were talking about using the `bookdown::bs4_book()` theme - it looks like this is currently only available in the development version of bookdown, so we'd need to install bookdown from github until v0.22 is released

**Comment by cansavvy** [comment]
We can add this as a possibility in the Dockerfile and document how to switch that in `getting_started.md`. I generally like to avoid development versions until they are officially determined to be stable. Do we know when v0.22 should be released approximately?

**Comment by KatherineCox** [comment]
Yeah, I understand wanting to be careful about using dev versions.

From a quick look around the bookdown repo, I can't tell when it'll be released.

- Last release was October 2020, so it's been kind-of a long gap (previous releases were coming out every ~couple of months)
-  Milestone for v0.22 says April 30th but I've no idea how meaningful that is, and they don't seem to really be using Milestones to track issues.

**Comment by KatherineCox** [comment]
[v0.22](https://github.com/rstudio/bookdown/releases/tag/v0.22) is out!

**Comment by cansavvy** [comment]
The docker image is using bookdown 0.24 so bookdown::bs4_book() is available.
