### ISSUE TITLE
Workflow guidance (in getting-started)

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/OTTR_Template#45]
Since you need to make a commit and PR anyway to finish setting up the GitHub rules, it might be nice to walk people through their first two commits, making some of the initial changes to the template (e.g. setting the title).  This helps make sure they don't miss things and lets people see the usual workflow in action.

One way to do this:

## First commit

Under ## Creating your Course, before ### Recommended repository settings, walk people through a first commit:
- Edit README.md (does not require Docker, can do this right in GitHub).
- Be sure to choose "Create a new branch for this commit..."
- submit pull request
- merge

Then carry on with ### Recommended repository settings
(since you've already filed a PR, then you should be able to check all the boxes now, correct?)

## Second commit

After the Docker instructions and before ## Citations, add a ## Recommended Workflow section, walking people through their second commit, roughly:

(clone the repo if you haven't already)

1. make new branch: `git checkout -b my-new-branch`
1. start up Docker `docker run -it -v $PWD:/home/rstudio -e PASSWORD=<CHOOSE_PASSWORD> -p 8787:8787 jhudsl/course_template`
1. In a browser, navigate to `localhost:8787` and enter username (`rstudio`) and the password you picked in the docker command.
1. Edit `index.Rmd`
	- YAML
		- title
		- author(s)
		- description
	- "# About this course"
1. Edit `About.Rmd`
1. Edit `_bookdown.yml`
	- book_filename
	- repo
1. [any other quick initial changes?]
1. `bookdown::serve_book()`
	- About this Course (first section) should have updated (`index.Rmd`)
	- About the Authors (last section) should have updated (`About.Rmd`)
	- Anything thing that should be checked for `_bookdown.yml`?

1. (Back on your computer, outside the Docker container)`git add .`
1. `git commit`
1. `git push -u`
1. [make any additional edits, builds, commits, and pushes]
1. [exit docker?]
1. [merge main into branch? or is this done automatically with the PR?]
1. on GitHub, open pull request
1. on GitHub, someone approves the PR
1. on GitHub, merge the PR
1. Delete the branch
1. Locally, switch back to main branch AND git pull
	- `git checkout main`
	- `git pull`
1. Delete your local copy of the branch `git branch -d my-new-branch`

I'm not sure I've got everything quite correct, a lot of this is new to me - I've mostly worked in small personal repos, so I haven't done too much with PRs, GitHub's repository settings, or GitHub actions.

**Comment by cansavvy** [comment]
Thanks for this @KatherineCox , I have been working on setting up this kind of information (though perhaps not to this level of detail yet) as issues that can be set up: #43 I think perhaps we can combine these strategies!

**Comment by cansavvy** [comment]
I'm hoping that what I've added with the issue filing and getting_started.md that this is addressed. If we find that is not true, then we can reopen later.
