### ISSUE TITLE
Layout more specific guidance on images

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#47]
Right now we are generally linking to GoogleSlide images. Because this keeps image changes updated, we probably want to stick with this strategy (and also keeping all image together in one slide deck). 

But besides that, we shouldl determine and add to `getting_started.md`: 

- How big does the Google slide need to be? (I made one extra large 1400 x1400 pixels so the res would be better). 
- How should images be specified? (right now I've been using html img src like below because it comes out well in bookdown)
- How should width/height other parameters be specified? Would it be better in markua if this were specified as a percentage or something else? 

Example:
```
<img src=https://docs.google.com/presentation/d/1cd434bkLer_CJ04GzpsZwzeEA9gjc5Ho6QimiHPbyEg/export/png?id=1cd434bkLer_CJ04GzpsZwzeEA9gjc5Ho6QimiHPbyEg&pageid=gcdcbd8d802_0_173 width = 400 height = 400 />
```

**Comment by cansavvy** [comment]
This issue will be generally informed by @muschellij2 ‘s resolutions of https://github.com/jhudsl/ITCR_Course_Template_Leanpub/issues/22

**Comment by KatherineCox** [comment]
Related, can we automate [this process](https://www.evernote.com/shard/s425/client/snv?noteGuid=fd22f17a-5b1e-c3d6-eb85-e47c20aa4b1d&noteKey=58951432cb4f6f996ad9a28df6852248&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs425%2Fsh%2Ffd22f17a-5b1e-c3d6-eb85-e47c20aa4b1d%2F58951432cb4f6f996ad9a28df6852248&title=Google%2Bslides) for converting the slide link?  It's kinda annoying to do it by hand if you've got a bunch of slides.  (Thanks for adding those instructions to the `getting_started`, they're super helpful!)

Here's one way to do it, just sticking a function at the top of the chapter:

````
---
title: "Chapter title"
output: html_document
---

```{r include=FALSE}
# store the id of my complete presentation
gpres <- "162GS7ArBPM4w_rPazcUrpnoEKT7jx9i7fpPQkH_iC_0"

google_slides_image <- function (presentation_id, slide_id) {
  paste0("https://docs.google.com/presentation/d/", presentation_id, "/export/png?id=", presentation_id, "&pageid=", slide_id)
}

```

# Google Slide Images

Here is an image from a Google Slide

```{r echo=FALSE}
knitr::include_graphics(google_slides_image(gpres, slide_id="gd5c49c5c55_0_165"))
```

Here is the same image using `img src`

<img src=`r google_slides_image(gpres, slide_id="gd5c49c5c55_0_165")`>

````

**Comment by cansavvy** [comment]
@KatherineCox This is great! I like this idea. I assum all renders fine by bookdown? If yes, do you mind adding this to the getting_started.md and the template Rmd? Either here or the DaSL template is fine and I can file a separate PR for the other one.

**Comment by KatherineCox** [comment]
Yes, I can do that!

Both methods render fine with bookdown for me - I'm using the ITCR Docker image on my own computer.  Haven't run it through the GitHub build (still need to fix my GitHub actions) but I don't see why there would be a problem.

This (ITCR) is the repo you've mostly been working on, right?  I'll add it here?

Should I also it to `03_test-cases so we can see how it turns out in Leanpub?

**Comment by cansavvy** [comment]
> Yes, I can do that!

Thanks!

> Both methods render fine with bookdown for me - I'm using the ITCR Docker image on my own computer.  Haven't run it through the GitHub build (still need to fix my GitHub actions) but I don't see why there would be a problem.

As long as it renders fine with bookdown, the GitHub actions run that same thing. 

> 
> This (ITCR) is the repo you've mostly been working on, right?  I'll add it here?

Yes! That'd be great. We're looking into re-combining the DaSL and ITCR template repos for maintenance purposes. Let me know if you have comments on this plan. See https://github.com/jhudsl/ITCR_Course_Template_Bookdown/pull/81

> 
> Should I also it to `03_test-cases so we can see how it turns out in Leanpub?

Yes! That's be great. From my discussions with @muschellij2 it sounds like `knitr::include_` functions should work fine but it would be great to have that in there for an official test. 

I might add your function noted with my other Google slide functions that I'm working on putting together as a package for easy importing. But there also might already be a didactr or leanbuild function that does this kind of thing?

**Comment by KatherineCox** [comment]
> I might add your function noted with my other Google slide functions that I'm working on putting together as a package for easy importing. But there also might already be a didactr or leanbuild function that does this kind of thing?

Yes, I imagine there's a better home for it than copying the function into every chapter :).  If you've got a good place for it, go for it.  Just let me know how/where to reference it if it gets put into a package somewhere.

**Comment by muschellij2** [comment]
It should be in https://github.com/jhudsl/leanbuild.  For Google slides, the function is `leanbuild::include_slide`.  Make sure to set `overwrite = FALSE` if you don't want it to download every time.

**Comment by KatherineCox** [comment]
Great!  Sounds like the best way to go, then if John ends up making any adjustments to play nicely with leanpub he can just make those changes in `leanbuild` and we won't have to worry about updating the .Rmds

@cansavvy can we include `leanbuild` in the Docker image?

**Comment by muschellij2** [comment]
- If you're embedding images, then you need to have alt text in the bracket.  If you are doing `<img src` then you need to do `<img src="blah.png" alt="SOMETHING">` (which will transform in to below):
```
{alt: "THIS IS ALTERNATIVE Text"}
![this is a caption, not an alt text](blah.png)
```

If using `knitr::include_graphics`, you must define `fig.alt` in the code chunk options/parameters to pass to `knitr`.

As `leanbuild::include_slide` is a loose wrapper for downloading the PNG and then using `knitr::include_graphics`, the same policy applies to using that function.

If you are including graphics your own way using Markdown, you *must* have the `{alt: }` tag immediately before it.
