### ISSUE TITLE
Learning objectives format?

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#48]
Do we want learning objectives to always be in a slide format or text or are we not specific on either?

**Comment by KatherineCox** [comment]
Some thoughts:

- Text would be more parsable, if we ever wanted to do anything that pulled out and displayed the learning objectives somewhere.  I don't have a specific use in mind, so I'm not sure whether that should actually be a consideration, but it keeps the option open.
- On the other hand, if we wanted the learning objectives to be in videos as well as the front of the chapter, it makes more sense to put them in slides.  Are we likely to generally want a video-per-chapter (even if it's just a quick intro / overview), or does the "book" provide the intro / overview, and videos are more for specific pieces of content?

**Comment by cansavvy** [comment]
I'm also inclined to stick with text instead of a slide. Easier to edit. Does @carriewright11 have thoughts?

**Comment by KatherineCox** [comment]
For text appearance, at least within `bookdown` there's the option of adding some styling to make them stand out with this syntax:

`## Learning Objectives {.learning-objectives}`

and then a css file with e.g. (make the font in that section blue, just as an example)
```
.learning-objectives {
   color: blue;
}
```

A quick look at the leanpub markua spec suggests that markua would effectively ignore the `{.learning-objectives}`, so we'd lose the formatting but not break things:

> "Any line outside of a code resource which starts with an opening curly brace { and ends with a closing curly brace } is assumed to be an attribute list, and will not be output by Leanpub...If Leanpub cannot handle the attribute list in the given context, it should just ignore the attribute list and add a warning to any list of warnings when generating the book."

**Comment by carriewright11** [comment]
This is a good question- I was actually currently using the ITCR slide template to make mine. https://jhudatascience.org/ITCR_Cancer_Research_Leadership/guidelines-for-multidisciplinary-informatics-teams.html
I figured that way the video from the slides would have more information. Maybe we should ask Jeff about this.

**Comment by cansavvy** [comment]
This will be relevant to the mechanics for transferring from bookdown to Leanpub. I'm fine with either, but whatever we choose we should probably be consistent.

And it does sound like no matter what we'll still need the learning objectives as a slide, so maybe the slide strategy makes sense?

**Comment by carriewright11** [comment]
Yeah, I think that makes sense for now.

**Comment by cansavvy** [comment]
Okay so let's go with slides for learning objectives, I'll follow @carriewright11 's format she's been using in ITCR_Research_Leadership. 

I'll switch over my learning objectives in ITCR_Documentation_and _Usability to be slides and I'll add a blurb in `getting_started.md` about this. 

This will probably be easier for transferring to Leanpub purposes anyway. (I think).
