### ISSUE TITLE
rendering error thoughts

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#488]
Occasionally I get this error... but I wonder if it should be flagged as an error.
![](https://user-images.githubusercontent.com/23014755/156257608-30257e3e-bb1b-455c-90cb-3798a804452c.png)

**Comment by cansavvy** [comment]
Can you link me to where this happened most recently? I sent out a fix for it, but I'm wondering if it got incorporated into the repo this came from.

**Comment by carriewright11** [comment]
ah ok I just had it for the [computing ITCR course](https://github.com/jhudsl/Computing_for_Cancer_Informatics)... but I have a sync waiting cause it has an error and I wanted to finish the course very soon

**Comment by carriewright11** [comment]
glad to hear you already fixed this! It's probably fixed by this [sync](https://github.com/jhudsl/Computing_for_Cancer_Informatics/pull/58)?  I will work on doing the sync now

**Comment by carriewright11** [comment]
looks like the error comes from not having the config_automation.yml file yet

**Comment by cansavvy** [comment]
Yes, I had the config_automation.yml file in there but didn't want it to overwrite people's existing config_automation.yml so I removed it from the sync

**Comment by carriewright11** [comment]
Right makes sense... I was just a strange case (like other old repos) where I never had that file/

**Comment by cansavvy** [comment]
https://raw.githubusercontent.com/jhudsl/OTTR_Template/main/config_automation.yml

You can add it manually

**Comment by carriewright11** [comment]
I did already :) thanks!

**Comment by carriewright11** [comment]
This is probably fixed, so I will close this issue. If I encounter the error again, I will let you know.
