### ISSUE TITLE
Authorization for rgoogleslides fails when in the docker container

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#49]
### Summary 

When I try to run `rgoogleslides::authorize()` inside a docker container, after I click `Allow` this happens: 
This is true no matter the browser I use. 

![Screen Shot 2021-04-20 at 3 49 25 PM](https://user-images.githubusercontent.com/23458084/115556687-ecf52580-a27e-11eb-84f0-63e840ab4ea8.png)

So if we do need to use `rgoogleslides`, which I think we will, I'll have to figure out a work around for this that allows us to still use the docker container.

**Comment by cansavvy** [comment]
So if I set up the `.httr-oauth` file outside of Docker, and then go back to Docker, I can use rgoogleslides fine because it just pulls that authorization. I don't love this, and feel like there should be a better way around it but I don't know enough about firewalls and etc to have yet come up with a more elegant solution. 

Will have to do some more digging. I haven't pinpointed the exact problem of why Docker is blocking the authorization or how to stop it from doing that.

**Comment by cansavvy** [comment]
Been trying to dig into this problem more. Don't really have leads for solutions. I know that rgoogleslides is using the R package: `httr`  to get authorization and this uses something called Oauth2 token authentication to do this. 

I also know that you can't seem to run from command line: `Rscript -e "rgoogleslides::authorize()"` because it won't successfully open the interactive window it needs.

**Comment by muschellij2** [comment]
You need to pass in the token, it's default is `NULL` in `rgoogleslides::authorize`:

So you need to do (assuming token is in `.httr-oauth` or wherever mounted on Docker:
```r
token = readRDS(".httr-oauth")
if (inherits(token, "request")) {
    token = x$auth_token
}
rgoogleslides::authorize(token = token)
```

or simply `Rscript -e "rgoogleslides::authorize(token = readRDS(".httr-oauth"))`

Also may not be relevant, but another snag may that you want to try `library(rgoogleslides); authorize(token=token)` because of the behavior of that package's `.onLoad`: https://rdrr.io/github/hairizuanbinnoorazman/googleslides/src/R/zzz.R, which only gets executed.  That could be wrong, but worth a shot.

**Comment by cansavvy** [comment]
Thanks! This is helpful! But my main concern is how to instruct people to set up the `.httr-oauth` file in the first place? Is there a not janky way to have someone collect that file or token for their own account?

**Comment by cansavvy** [comment]
Maybe this or something like it would be helpful? https://cran.r-project.org/web/packages/googleAuthR/vignettes/google-authentication-types.html

**Comment by muschellij2** [comment]
Yes, but I'd say, run `token = rgoogleslides::authorize(); saveRDS(token, file = "auth-place.rds")` or wherever you'd like to place the token rds.  You can also see https://gargle.r-lib.org/articles/non-interactive-auth.html for some other options, but `rgoogleslides` doesn't live in the `gargle*` family, but can take the client ID and secret from https://rdrr.io/github/hairizuanbinnoorazman/googleslides/src/R/zzz.R and use `gargle`.

**Comment by cansavvy** [comment]
> Yes, but I'd say, run `token = rgoogleslides::authorize(); saveRDS(token, file = "auth-place.rds")` or wherever you'd like to place the token rds.  You can also see https://gargle.r-lib.org/articles/non-interactive-auth.html for some other options, but `rgoogleslides` doesn't live in the `gargle*` family, but can take the client ID and secret from https://rdrr.io/github/hairizuanbinnoorazman/googleslides/src/R/zzz.R and use `gargle`.
> 

This is great! Will workshop this tomorrow!

**Comment by cansavvy** [comment]
I'm still finding the easiest way to get the `httr-auth` file is to just run through the authorize steps in a non-docker container and then push that file to github. I think this is what I will write in the getting_started.md as the steps for getting a Google Slides going. 

These other options require Google Cloud Developer accounts or a lot of extra steps that seem more complicated and like a bigger hurdle than just generating the `httr-auth` file outside of Docker.

**Comment by cansavvy** [comment]
So we can't just upload the httr-oauth file. My next idea is to just store the rgoogleslides token as a GitHub secret. That wouldn't help people out for local development necessarily but would make the github actions work fine. 

I guess I need to think more about how often this script would need to be run locally if github actions really is doing the heavy lifting.

**Comment by cansavvy** [comment]
My other concern is the set up for these courses from this template is growing more cumbersome the more github secrets we have. Probably also need to add some guidance about how to delete or modify some of these github actions if a course doesn't want or need them. Will make a new issue for that.

**Comment by cansavvy** [comment]
Ah. What if we supply the token upon building the Docker container through a Docker secret? 
https://stackoverflow.com/questions/59143685/consume-secret-inside-dockerfile
https://docs.docker.com/engine/reference/commandline/secret_create/

**Comment by cansavvy** [comment]
My next plan or idea is looking into if there’s any easy way to grab GitHub secrets for local use if you have the right set of permissions. 
Maybe this: https://git-secret.io/ has some useful functionality for this.

**Comment by cansavvy** [comment]
I tried to just supply the token that I get from the interactive bits from rgoogleslides::authorize to `token` and at first it seems like it works but when you try downstream functions, it can't get access. 

I didn't want to, but I did set up a Google API credentials to try that way, it seems like way more nonsense than we need and I don't want other future developers to have to do that. 

I want to be able to supply just the token to `rgoogleslides::authorize()` but that doesn't work. It wants output from [oauth2.0_token()](https://www.rdocumentation.org/packages/httr/versions/1.4.2/topics/oauth2.0_token) but I can't see a straightforward way to programmatically get that. 

I'm trying to not involve a bunch of other packages. But maybe I'll have to.

**Comment by cansavvy** [comment]
My main goal is to get a piece of text I can supply to `rgoogleslides::authorize()` this way I can store it as a GITHUB secret and be done.

**Comment by cansavvy** [comment]
So very close to solving this. The authotization appears to work locally but even though I updated the GIT secret for the token, I'm getting the same kind of downstream error that it gives when you give it a token that doesn't actually work: https://github.com/jhudsl/ITCR_Course_Template_Bookdown/runs/2477671770?check_suite_focus=true

**Comment by cansavvy** [comment]
This is solved as well!
