### ISSUE TITLE
Be able to set style options through config_automation.yml

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#493]
Related to #453 

It would be great to have style items easily set through config_automation.yml 

Especially for people like myself who don't feel confident about adjusting style by hand, it would be great to have some options in config_automation.yml to make it easier to adjust.

**Comment by cansavvy** [comment]
This would probably be a thing that @carriewright11 and myself could pair on to get done.

**Comment by carriewright11** [comment]
yeah! sounds like a great idea

**Comment by kweav** [comment]
Does this include things like with the AI for Decision Makers where @avahoffman had to edit the yml for the TOC capitalization? Are you thinking different variants where one is uncommented, but the rest are still there with explanations of which block will do what?

**Comment by avahoffman** [comment]
I think the capitalization thing might have been a bug - not sure we've ever had a case where we wanted the first H1 section in all caps.

Are you thinking things like color scheme @cansavvy ?

**Comment by avahoffman** [comment]
Linking the commit because I couldn't remember what the issue was at first 😛 

https://github.com/fhdsl/AI_for_Decision_Makers/commit/c7cfdc46c313cd8966a4a3a54cd1291d61d1f4ff

**Comment by cansavvy** [comment]
Yeah the original inspiration was thinking of the most common style use cases and making it easy for users to specify through adding something to the config_automation.yml 

So some example ideas: 
- Turning TOC off or on 
- Picking a style set 


The thing we don't want to do is just have everything copied from the config_automation.yml to CSS but if we can find some key easy options to set that would be good.

In my mind, this is a lower priority but *nice to have* feature.

**Comment by avahoffman** [comment]
Another thing: being able to turn the big caps off. I usually just delete it from the css but others might not know where it is. 90% of the time I end up with an awkward situation like:

![image](https://github.com/jhudsl/OTTR_Template/assets/15618412/5bd47d9e-2056-454f-b19b-1fd634b9a6f2)

**Comment by carriewright11** [comment]
ah yes, I think both would be great - perhaps we should have a separate issue for both - I think Ava's caps suggestion might be more pressing

**Comment by cansavvy** [comment]
This is generally addressed.
