### ISSUE TITLE
Have URLs periodically checked

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#501]
I'd love to have something that periodically checks the urls on my courses even if I haven't filed a pull request and then if can alert me to broken ones that would be perfect. 

I know this is possible with GitHub actions, I'd just need to set it up.

**Comment by cansavvy** [comment]
I'll make this a priority too because it should be a fairly quick add. *should*....

**Comment by cansavvy** [comment]
That was a lie. I did not make this a priority. But now this would be a good issue for @howardbaek to do to get familiar with OTTR. So let’s chat about it.

**Comment by howardbaik** [comment]
[This post](https://andrewwegner.com/find-broken-links-with-github-actions.html) suggests a GHA for periodically checking for broken links using the `schedule` [event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule).

Also, it seems like GHA natively sends email notifications: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs

**Comment by cansavvy** [comment]
The other thing that would be great for this, is to have it create a new branch and file a pull request that tells someone what the broken URLs are. That way there's already the branch they can check out to fix it. 

Grab code from here: 
https://github.com/jhudsl/OTTR_Template/blob/main/.github/workflows/pull_request.yml
