### ISSUE TITLE
URL checker action is not cooperating with Rmds anymore

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#514]
Even though I've tried going back to earlier versions of https://github.com/urlstechie/urlchecker-action/tree/0.2.3, it still is not cooperating with scanning Rmds anymore. It always tells me "no URLs detected"

I think this is because https://github.com/urlstechie/urlchecker-action/blob/master/entrypoint.sh hasn't frozen what version they use and updates to the python urlchecker pacakge that is underneath the hood: https://quay.io/repository/urlstechie/urlchecker/manifest/sha256:65edb42c5fda47c6b8668cee59b59d1eeb9e2b432711cdd3415bc569cfcfd635

SO, I think we should just switch strategies, and maybe use the package they use directly instead of using their action.

**Comment by avahoffman** [comment]
Is this by chance related to images not rendering?

![image](https://user-images.githubusercontent.com/15618412/160902324-fed55b7d-b75f-464d-aef8-678b7a7ce3c1.png)

**Comment by cansavvy** [comment]
The fix for this is pushed, I'm just testing it out on various repositories before I send out the next release.

**Comment by cansavvy** [comment]
It's working! The only thing left is to provide a way for url's to be ignored, but I think this can be a later priority. Going to make a new issue for this.
