### ISSUE TITLE
Examples of different kind of embeddings

### ISSUE THREAD

**Issue by muschellij2** [jhudsl/OTTR_Template#52]
I have created https://github.com/muschellij2/ITCR_Course_Template/blob/main/03-test_cases.Rmd to try to get some test cases in there can  you @cansavvy @carriewright11 maybe think of some other cases?  The really nice thing of the include_url is that if it's youtube, it puts the snapshot for you in there!

**Comment by cansavvy** [comment]
You want us to add different ways of adding images or other media?

**Comment by muschellij2** [comment]
I think flesh out the ways you'd add in examples - the test rmd is now in the main

**Comment by cansavvy** [comment]
If the guidance in #87 is okay, I think we'll be able to close this issue as well.
