### ISSUE TITLE
failing tocless render with multiple CSS files

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/OTTR_Template#536]
I'm running into trouble with the tocless render if I have multiple CSS files

## What I'm trying to do:
Currently AnVIL_Template uses a customized css file, but there's really only a couple of things we've changed from OTTR template style.  To make it easier to incorporate OTTR style updates like the great new callout boxes, I thought it would be a good idea to switch back to using the OTTR style.css, and then just override those few things in a separate anvil.css file i.e.

```
bookdown::gitbook:
  css: [assets/style.css, assets/AnVIL_style/anvil.css]
```

This appears to work for the first robot render (I haven't been able to view the output but it at least doesn't fail), but it fails during the tocless render.  Short-term I could just turn off tocless and/or manually update our existing css file, but it'd be nice to get this working if it's not too painful.

## Links and details

Here's the PR: https://github.com/jhudsl/AnVIL_Template/pull/106
And the failing GHA run: https://github.com/jhudsl/AnVIL_Template/runs/6117628854?check_suite_focus=true

CSS files I've been experimenting with:

- `assets/AnVIL_style/style_anvil.css` - full, anvil-customized version of style.css. which we've been using successfully up 'til now.  I'd like to get rid of this
- `assets/style.css` (identical to OTTR)
- `assets/AnVIL_style/anvil.css` - new, tiny css file containing the few anvil-specific customizations, intended to be used in conjunction with `style.css`

If I use any of those 3 files alone it renders without a problem, but if I use a list of the two files I want `[assets/style.css, assets/AnVIL_style/style_anvil.css]` it fails.

**Comment by cansavvy** [comment]
Oh yeah, the tocless render depends on the name of the css file being just that one css file. I can make it more accommodating though.

**Comment by kweav** [comment]
Is this still an active issue?

**Comment by cansavvy** [comment]
I believe this has been addressed!
