### ISSUE TITLE
Who should be gitblamed for syncs?

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/OTTR_Template#557]
Noticed that @cansavvy you are comming up as committing the changes when I launch a sync from AnVIL Template.

It should probably be github actions, jhudsl robot, or ideally, whoever launched the sync so we can trace changes back. 

![image](https://user-images.githubusercontent.com/15618412/186731717-00f0d5d1-d245-4f8b-ad36-a12ebbca58aa.png)

**Comment by cansavvy** [comment]
I think all we need to switch this is change the PAT to be from jhudsl-robot. Right now our jhudsl organization is using a PAT from my account.

**Comment by cansavvy** [comment]
I just changed the GH_PAT for this organization to be from jhudsl-robot so let's see if that fixes this.

**Comment by avahoffman** [comment]
Yep! Fixed! https://github.com/jhudsl/AnVIL_Template_Test/pull/12

**Comment by KatherineCox** [comment]
Nice!  I'd been meaning to ask about that.
