### ISSUE TITLE
small problem with spell check

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#580]
## Describe what is not working with the template or is unclear in the documentation

I noticed some unusual spelling check activity since the update.

## Please link to the specific course repository you are working on
https://github.com/fhdsl/NIH_Data_Sharing/pull/11#partial-pull-merging

## To Reproduce

Not sure if I could reproduce it... except that I noticed the spell check artifact file in the comment gave a 404. Maybe this was just a timing issue of when the preview branch got deleted or something idk. But maybe we should let people know that this could happen?
In any case it went away and the report showed when I pushed a new change to the PR.
## Expected behavior

Expected to have a report for spelling instead of a 404 message.

## Github actions links

https://github.com/fhdsl/NIH_Data_Sharing/actions/runs/3275800321/jobs/5391093530

a message of: shell: bash --noprofile --norc -e -o pipefail {0}

But I think this happened when it did produce a report too, right after.

**Comment by carriewright11** [comment]
also would be cool if we could make sure text in the yml isn't included in the spell check - I hadn't seen that be an issue before but came up this time a bit.

**Comment by cansavvy** [comment]
I think I fixed this problem: https://github.com/jhudsl/ottr-reports/pull/7
And #582 

@carriewright11 can you retry this and see if it’s fixed? Or just otherwise keep an eye on if it’s fixed?

**Comment by carriewright11** [comment]
Cool, thanks!- will see if it happens anymore!

**Comment by cansavvy** [comment]
I think I know why this is happening. I think it's because of the complete refresh of the preview branch that we do. So for now I'm going to make it so the comment says that the check is still running so that people know they have to wait to get the updated results.

**Comment by carriewright11** [comment]
> I think I know why this is happening. I think it's because of the complete refresh of the preview branch that we do. So for now I'm going to make it so the comment says that the check is still running so that people know they have to wait to get the updated results.

that makes sense... sounds good

**Comment by cansavvy** [comment]
This *should* be addressed but we can reopen if it is still a problem. Addressed by https://github.com/jhudsl/ottr-reports/pull/8 and https://github.com/jhudsl/ottr-reports/pull/9

**Comment by carriewright11** [comment]
I see something similar here: https://github.com/fhdsl/NIH_Data_Sharing/pull/14  - I wonder if we need to tell people to make another change... this currently gives a 404 and the last commit was yesterday.
![Screen Shot 2022-10-21 at 1 24 50 PM](https://user-images.githubusercontent.com/23014755/197253855-b63e56cc-f278-4d3c-bb3d-ec00c508c7d2.png)

**Comment by cansavvy** [comment]
This problem should be resolved but you might still see the issue if the pull request predates the fix. (The fix happened just today).

**Comment by cansavvy** [comment]
Another item I realized that affects this is make sure your gitignore doesn’t have spell_check_results.tsv in it. OTTR_Template had that and it was affecting things.

**Comment by carriewright11** [comment]
> Another item I realized that affects this is make sure your gitignore doesn’t have spell_check_results.tsv in it. OTTR_Template had that and it was affecting things.

Oh ok - I will check that for this repo

**Comment by carriewright11** [comment]
> 

oh gotcha - thought it was yesterday :P

**Comment by cansavvy** [comment]
> > Another item I realized that affects this is make sure your gitignore doesn’t have spell_check_results.tsv in it. OTTR_Template had that and it was affecting things.
> 
> Oh ok - I will check that for this repo

https://github.com/fhdsl/NIH_Data_Sharing/pull/15

**Comment by cansavvy** [comment]
> oh gotcha - thought it was yesterday :P

Part of the fix I implemented yesterday but I identified one more problem today. Hopefully this is the end to this problem for real. We will just have to keep an eye out on repositories for the gitignore thing.
