### ISSUE TITLE
Problem with url checker 

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#581]
## Describe what is not working with the template or is unclear in the documentation

The URL check failed, yet the comment still says no broken urls.

## Please link to the specific course repository you are working on

https://github.com/opencasestudies/OCS_Guide/pull/180

## To Reproduce

Not sure if I could reproduce this... but just tried doing a sync update with the now workflows.

## Expected behavior

Would expect a report to show up for the URLs, however I don't think the report could be generated because of this missing values error.

## Github actions links

https://github.com/opencasestudies/OCS_Guide/actions/runs/3266002333/jobs/5369107187

## Screenshots

<img width="956" alt="Screen Shot 2022-10-18 at 3 49 10 PM" src="https://user-images.githubusercontent.com/23014755/196529749-72c27c5d-fc6d-47cf-a4ff-c038479de8a3.png">
 
## Additional context

This was done on the OpenCaseStudies organization, not jhu or fh.

**Comment by cansavvy** [comment]
I've found another instance to this error: https://github.com/datatrail-jhu/DataTrail/actions/runs/3283835104/jobs/5409063044 so hopefully i'll be able to get to the bottom of it now.

**Comment by cansavvy** [comment]
This *should* be fixed. We will reopen if it happens again. https://github.com/jhudsl/ottr-reports/pull/8
