### ISSUE TITLE
References must be at the end currently - Can we make this more flexible?

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#594]
I think we might need to describe this better in the documentation- but maybe I just missed where we have this :P 

If you move the references rmd file in tbe _bookdown.yml it doesn't actually change the location - the references still appear at the end.

**Comment by carriewright11** [comment]
I am adding documentation for this now

**Comment by cansavvy** [comment]
Does #23 cover this issue? Can it be closed now?

**Comment by carriewright11** [comment]
Not quite.. Want to add info about `split_bib: no` option to suppress references at the end of each chapter

**Comment by carriewright11** [comment]
I can do this
