### ISSUE TITLE
people might push docs changes

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#597]
It would be nice to avoid people pushing changes to docs.

- Maybe we should have the docs dir in the gitignore and then just have the gitactions robot force commit the changes? 
- otherwise, we could at minimum tell people not to push those changes (should we do that for now?)

**Comment by carriewright11** [comment]
I'd be happy to add it to the documentation if we think this might take a bit of time @cansavvy

**Comment by cansavvy** [comment]
@carriewright11 what was the motivation behind this idea? We can easily set the GHA so they only re-render for changes to certain files, but what was the original problem that motivated this issue? That might inform the strategy we take here.

**Comment by carriewright11** [comment]
Hi @cansavvy , Amy had pushed changes to the docs folder (from locally rendering) to her first ottrfied repo and then it caused her lots of confusion

**Comment by cansavvy** [comment]
Gotcha. So it shouldn't have triggered a rerender but obviously it would be confusing since her changes would be overwritten by the render. So this seems like primarily a documentation problem so I'll look at the wording on ottrproject.org

**Comment by carriewright11** [comment]
yeah - I think people are used to pushing all locally changed files but then it  can cause git conflicts in lots of files if a render happened for another pull request that changes the docs files remotely and they don't match

**Comment by carriewright11** [comment]
of course this only happens if they are also rendering locally too

**Comment by cansavvy** [comment]
I think the gitignore and the documentation is all we can do here unless there’s something else we should do. What do you think @carriewright11 is this addressed or is there something else?

**Comment by carriewright11** [comment]
I see that you added docs/* to the gitignore 3 months ago - indeed that is what I thought was needed
