### ISSUE TITLE
Warnings about GHAs (`checkout@v2`, `ubuntu-latest`)

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/OTTR_Template#604]
(Copied from a run on AnVIL_Template)
> [Load user automation choices](https://github.com/jhudsl/AnVIL_Template/actions/runs/3642347095/jobs/6149344708)
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

> [Render all output courses: .github#L1](https://github.com/jhudsl/AnVIL_Template/commit/ef281629d5156632b28ed8e8de4f2d45e091467d#annotation_6824521525)
> ubuntu-latest pipelines will use ubuntu-22.04 soon. For more details, see https://github.com/actions/runner-images/issues/6399

> [Render bookdown](https://github.com/jhudsl/AnVIL_Template/actions/runs/3642347095/jobs/6149364405)
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

From the links, looks like we have until Summer 2023 to update Node.js, and March 2023  to confirm ubuntu-latest isn't a problem.

Also related: #584

**Comment by cansavvy** [comment]
I've done some preliminary work on this but haven't found the most elegant solution. This probably should be bumped in priority since this is happening this year and affects soooo many repositories.

**Comment by cansavvy** [comment]
This is related to this too: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by cansavvy** [comment]
I've not been able to find the warning messages posted above. Can you add a screenshot that shows me where you saw them specifically, @KatherineCox ?

**Comment by cansavvy** [comment]
Ah I found them: 
<img width="600" alt="Screen Shot 2023-01-31 at 12 01 37 PM" src="https://user-images.githubusercontent.com/23458084/215831263-ae8f0c1d-00bd-4ed6-b9a2-fc6a56a94b86.png">


Unfortunately I think this is up to the creators of the actions that we are using and there's not much that we can do but check if they have updated versions that use Node.js 16. 

I'll start going through to see if there are updated versions we can use. Oh boy.

**Comment by KatherineCox** [comment]
@cansavvy haha, you're ahead of me.  I was coming to show where I'd seen the warnings, and then to mention upgrading actions/checkout@v2 to v3, but looks like you're on top of things! :)

**Comment by cansavvy** [comment]
This should* be addressed now. The only thing that might not be is the OTTR-reports part. But we don’t have any direct `set-output` s there. So I think we’ve done what we can.
