### ISSUE TITLE
Trigger renders after a course is done to catch broken links?

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#606]
Noticed that old courses have quite a few broken links that we would like to catch, but we only do so when we try to re-render after making a change.

Perhaps we can trigger rendering periodically to check for these?

**Comment by cansavvy** [comment]
I think the heart issue is tracked previously here: https://github.com/jhudsl/OTTR_Template/issues/501

If the idea there doesn't cover this idea, let me know.

**Comment by cansavvy** [comment]
This is addressed with periodic URL checker!
