### ISSUE TITLE
jhudsl-robot git config error message when rendering website

### ISSUE THREAD

**Issue by stephaniemyan** [jhudsl/OTTR_Template#621]
I've been using the OTTR template to render an online textbook for a couple of months now and it's been working great so far. Yesterday I tried updating the website and started getting this error in the `Render bookdown` -> `Login as jhudsl-robot` step:

```
Run git config --local user.email "itcrtrainingnetwork@gmail.com"
  
  git config --local user.email "itcrtrainingnetwork@gmail.com"
  git config --local user.name "jhudsl-robot"
  shell: sh -e {0}
fatal: --local can only be used inside a git repository
Error: Process completed with exit code 1
```

You can view the action log [here](https://github.com/mccoy-lab/hgv_modules/actions/runs/4356184035/jobs/7613842258#step:4:8), and are welcome to try re-running the jobs if you'd like (I can upgrade `jhudsl-robot`'s permissions if you need me to!).

I haven't gotten this error before and am not sure how to go about fixing it, since it doesn't seem to be related to the webpage content itself:
* when I tried to re-render the website with an older version of the content (which worked just a few weeks ago), it failed with the same error as above
* I've also made sure that `jhudsl-robot`is a collaborator on the repo with the correct permissions

Any advice would be appreciated! Thanks for all the work you've put into this valuable resource.

**Comment by cansavvy** [comment]
Thanks so much for your comment and using OTTR!!

This is a bug from that comes downstream from some updates we had to make due to other github actions we use under the hood that are being deprecated, we sent out an OTTR template update that addressed this problem.

Did you follow the steps to Enroll you repository for OTTR updates? As described here on Step 9? https://www.ottrproject.org/getting_started.html#9%20Enroll%20your%20repository%20for%20OTTR%20updates

If not, no worries, I'm happy to help you with it.

**Comment by stephaniemyan** [comment]
I haven't but I will do that now and see if it fixes it! Thank you!

**Comment by cansavvy** [comment]
Once we get your repository enrolled in the updates, I'll need to manual set out an update to your repo. I'll do that tonight or tomorrow. 

Thanks again! Let me know if you have any troubles!

**Comment by stephaniemyan** [comment]
I just went through the steps to enroll for updates. Some of the Github interface looks different from when the instructions were made (I couldn't figure out how to request you as a reviewer, but I might have just missed something), so hopefully I did it right!

**Comment by cansavvy** [comment]
Yup! That was it. I merged it and will send over the updates. You'll see a pull request.

**Comment by cansavvy** [comment]
This was resolved with https://github.com/mccoy-lab/hgv_modules/actions/runs/4364753281/jobs/7632468928
