### ISSUE TITLE
URL checker gets thrown off by parantheses in a URL

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#631]
I don't have a great solution for this problem right now. But the url checker doesn't handle it when URLs have parantheses.

https://github.com/jhudsl/Ethical_Data_Handling_for_Cancer_Research/pull/46#issuecomment-1481543211

> > @cansavvy this broken url is confusing me... I think it has to do with having parentheses in the url again... maybe this repo just needs updating?
> 
> Unfortunately the URL checker get thrown off if there are parantheses in the URL. I dont think the URL is actually broken. We can try to add it to ignore-urls.txt to have it ignored. I'll make sure that this is recorded as an issue on OTTR_Template.

**Comment by KatherineCox** [comment]
Oh, I filed a similar issue in https://github.com/jhudsl/ottr-reports/issues/17 , although in my case I was trying to put the url inside parentheses.

**Comment by cansavvy** [comment]
Hey @howardbaek This is a problem that's been plaguing OTTR lately, we should chat about it. It would be great if you could look into a better solution for this.

**Comment by cansavvy** [comment]
See this example: https://github.com/jhudsl/Ethical_Data_Handling_for_Cancer_Research/blob/preview-46/check_reports/url_checks.tsv

**Comment by cansavvy** [comment]
For example: `https://en.wikipedia.org/wiki/Cache_(computing` fails because it has parantheses in it.

**Comment by cansavvy** [comment]
The change is going to need to be done in this script that is used by the ottr-reports: https://github.com/jhudsl/ottr-reports/blob/main/scripts/url-check.R 

We need all ways of specifying URLs as discussed in https://github.com/jhudsl/OTTR_Template/blob/main/02-chapter_of_course.Rmd to be covered. 

We want to only pull out the URL but not the other parts of the place we specified it. 

Currently we try to pull the URLs from the markdown documents, but after the rendering happens we could also pull the URLs from there but that would mean switching the order of doing rendering first and then checking for URLs. 

This might be fine but this would take a lot longer for some books that are big.

**Comment by avahoffman** [comment]
resolved by https://github.com/jhudsl/ottr-reports/pull/18

**Comment by howardbaik** [comment]
Sorry I couldn't get to this earlier! Glad to know its fixed.

**Comment by cansavvy** [comment]
> Sorry I couldn't get to this earlier! Glad to know its fixed.

No worries! It had been on my todo list a very long time before that. But @avahoffman got it done!
