### ISSUE TITLE
Add our courses to glittr

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#632]
[glittr]( https://glittr.org/?per_page=25&sort_by=stargazers&sort_direction=desc )
wonder if that can be automated at all - haven't done one yet though

**Comment by howardbaik** [comment]
Maybe we can programmatically fill in this form: https://glittr.org/contribute

**Comment by kweav** [comment]
@cansavvy should this be closed since a slack message from Sept says you've done this? 
@carriewright11 should this be added to the course checklist for new courses?

**Comment by cansavvy** [comment]
Yes! Thanks! It should be closed.
