### ISSUE TITLE
automatic checks after a class is finished

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#658]
it would be really cool to check a class for broken URLs periodically 

Currently unless we make new changes in a PR we don't usually catch them. 

would be great to get an email to fix them

**Comment by howardbaik** [comment]
Seems like GHA natively sends email notifications: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs

**Comment by kweav** [comment]
I think @cansavvy solved this with Issue #501 which is now closed
