### ISSUE TITLE
Creating a CONTRIBUTING.md doc for OTTR

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#706]
@kweav is going to work on this! 

This document would be for people who would like to help contribute to OTTR (may be just for us at first) 
Aka if someone wants to help with OTTR, what do we need to tell them? 

Things it should include: 

1. A breakdown of the different ottr repositories and what is where
2. How one can contribute --
    a. How to file pull requests for example and who to request. 
    b. How to go to issues and assign yourself and get started on something.

**Comment by KatherineCox** [comment]
Also make sure to add the `CONTRIBUTING.md` file to the list of files that get cleaned up when starting a new repository, in [`starting-course.yml`](https://github.com/jhudsl/OTTR_Template/blob/main/.github/workflows/starting-course.yml)
