### ISSUE TITLE
bump checkout@v3 -> v4

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/OTTR_Template#714]
Got this .. might need some updates [Load user automation choices](https://github.com/jhudsl/ITCR_Tables/actions/runs/7979956477/job/21788545144)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, doughepi/yaml-env-action@v1.0.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by cansavvy** [comment]
Yup. I know how to solve this problem. Just need to bump up the checkout action versions we are using. @howardbaek is this something you could do? 

Let me know if you need more details.

**Comment by howardbaik** [comment]
I'm guessing I need to bump up v3 to v4 in these lines? 
- https://github.com/jhudsl/ITCR_Tables/blob/main/.github/workflows/render-site.yml#L29
- https://github.com/jhudsl/ITCR_Tables/blob/main/.github/workflows/render-site.yml#L50

**Comment by cansavvy** [comment]
Yes! And anywhere else you find it!
