### ISSUE TITLE
Methods of writing content links don't work

### ISSUE THREAD

**Issue by williamtmillsiv** [jhudsl/OTTR_Template#726]
## Describe what is not working with the course
Clicking on links for instructions on how to write content for OTTR course produces 404 error

## Steps to Reproduce
1. Go to https://www.ottrproject.org/getting_started.html#starting-a-new-ottr-course
2. Click on 'Methods of writing content' from table of contents on left of page
3. Click [Jump to OTTR Entry Level instructions here](https://www.ottrproject.org/writing_content.html#ottr-entry-level) or [Jump to OTTR Advanced instructions here](https://www.ottrproject.org/writing_content.html#ottr-advanced)

## Expected behavior
Links should navigate to webpage with instructions for writing content to OTTR course

**Comment by cansavvy** [comment]
Thanks for this @williamtmillsiv ! Should be fixed soon. Have it fixed in https://github.com/jhudsl/ottrproject.org/pull/46

**Comment by cansavvy** [comment]
This is fixed and merged! Thanks.
