### ISSUE TITLE
Consistency between repo name and rproj file

### ISSUE THREAD

**Issue by howardbaik** [jhudsl/OTTR_Template#735]
Would be nice to have some consistency between the repo name and the `.Rproj` file

**Comment by cansavvy** [comment]
> Would be nice to have some consistency between the repo name and the `.Rproj` file

Can you talk more about what you mean about this? I'm on board, just want to know what you mean.

**Comment by howardbaik** [comment]
The repo is called `OTTR_Template` and the `.Rproj` is called `OTTR_template`.
