### ISSUE TITLE
Add info about mario to OTTR and wiki

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#74]
I know video tutorials can be made automatically from GoogleSlides, but I don't know how. This is something we should have described in `getting_started.md`

I'm not sure about the details about how this is done. @muschellij2 is this something you can give some guidance on? I don't mind writing documentation for it but would need to be sent information.

**Comment by muschellij2** [comment]
`didactr::gs_ari` or `ariExtra::gs_to_ari` will get you really close (need `ffmpeg` installed) and an API key for one of the synthesis engines (google, amazon, or microsoft)

**Comment by cansavvy** [comment]
This requires mario to be in a better spot.

**Comment by kweav** [comment]
What is Mario?
