### ISSUE TITLE
Where do figures go

### ISSUE THREAD

**Issue by muschellij2** [jhudsl/OTTR_Template#77]
I vote we say in every Rmd, if new_session = TRUE for bookdown (our default in _bookdown.yml), we do similar to: https://github.com/jhudsl/tidyversecourse/blob/master/05-prediction.Rmd#L4

```{r, include=FALSE}
knitr::opts_chunk$set(fig.path = "resources/images/COURSENAME-")
```

**Comment by muschellij2** [comment]
Why would we do it this way?  It fixes any issues of code-generated figures when copying over to `manuscript` for leanpub from what I can tell.

**Comment by muschellij2** [comment]
The other option is that we introduce a `_common.R`: https://github.com/rstudio/bookdown/issues/1049, but I havent' been able to get it to work yet

**Comment by cansavvy** [comment]
Is there a way we can set `fig.path` globally in the bookdown.yml? I'll look, unless someone knows off the top of their head.

**Comment by muschellij2** [comment]
That's what I was trying to do in _common.R, but I can't figure it out.

**Comment by muschellij2** [comment]
You must either do:
`````r
```{r, include=FALSE}
knitr::opts_chunk$set(fig.path = "images/YOURNAME-")
```
`````


`````r
```{r, include=FALSE}
fp = knitr::fig_path()
fp = dirname(fp)
fp = paste0("images/", fp, "/")
knitr::opts_chunk$set(fig.path = fp)
```
`````
