### ISSUE TITLE
Delete manuscript folder action is adding a script that shouldn't be there to the template

### ISSUE THREAD

**Issue by kweav** [jhudsl/OTTR_Template#789]
## Describe what is not working with the template or is unclear in the documentation
The [Delete manuscript folder action appears to be adding the `make-screenshots.R` script to the top of the OTTR_Template repository](https://github.com/jhudsl/OTTR_Template/commit/625defe0dea1423300a025ad0d9a349ed960edc4). Candace has seen this script and deleted it twice now and looking at [the history of the script file](https://github.com/jhudsl/OTTR_Template/commits/main/make_screenshots.R), the action appears to be adding it.

**Comment by cansavvy** [comment]
Addressed for now. And eventually this won't be a problem because of the refactoring that we are working on. https://github.com/jhudsl/ottrpal/issues
