### ISSUE TITLE
Thoughts: Keeping this and DaSL template updated concurrently is not great

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#80]
With only a few days of having DaSL and this template going, I'm finding the maintenance of both is a bit redundant and I'm worried about something falling through the cracks. 

Basically whenever I make a change here I have to make a change over on the DaSL and its not a great system. 
Not sure how or if there's a way to make this better, but I'm going to write this down in case anyone has ideas.

**Comment by jtleek** [comment]
I think we urgently need to consolidate the two templates into just the DaSL template and a set of diffs for ITCR. What do you think @carriewright11 @cansavvy

**Comment by cansavvy** [comment]
I think that's fine with me. I think we found through the process that the differences between the two templates is not actually that much.

**Comment by cansavvy** [comment]
We could have a separate `getting_started.md` for ITCR courses vs Others just to make the process more clear?

**Comment by cansavvy** [comment]
As well as we can make the differences more clear in the BaseCamp template and their associated ToDos.

**Comment by carriewright11** [comment]
I like that idea and maybe we can use rmarkdown templates that Katie has been suggesting so that aesthetics can be project specific. I am currently adding most of these with an _output.yml file for bookdown hopefully we could include that in an Rmarkdown template.

**Comment by carriewright11** [comment]
could consider submodules if we need to

**Comment by carriewright11** [comment]
but I'd rather do that if the other plan doesn't seem to be working

**Comment by cansavvy** [comment]
Agreed. I'm worried about submodules adding confusion for whenever we have more outside contributors trying to use the template.

**Comment by cansavvy** [comment]
So for a moving forward plan: 

With @KatherineCox input from working with the DaSL template, I think I'll take inventory of how DaSL and ITCR templates are different (I think its mostly text) and I'll draft up different instructions. These instructions will probably partially live in basecamp but maybe a short addendum here. 

Once people take a look at my draft of "branching off" instructions, if we feel that that would address the differences adequately, then I will rename this repo as DaSL_Course_Template_Bookdown and delete the current `DaSL_Course_Template_Bookdown`. (Simply because I have higher confidence this one, the ITCR one, is more up to date). 

Then all courses can just start from here.

**Comment by cansavvy** [comment]
Here's the differences between the DaSL and ITCR template repos: 

- The `README` has "ITCR" mentions 
- `_bookdown.yml` has "ITCR" mentions 
- The docker image is either `jhudsl/itcr_course_template` or `jhudsl/course_template` (but right now the images themselves are identical and can't foresee a reason they would differ much later. 
- `index.Rmd` has an intro paragraph about ITCR as well as the template title `Informatics Technology for Cancer Research (ITCR): Course Name`
- The google slide sets are different. 
- The logos are different. 

These are all pretty simple, I think we could just have one docker image and then keep an alternative versions of: 
- `index.Rmd` for ITCR/DaSL. 
- `_output.yml` for ITCR/DaSL. 
- `getting_started.md` can have links to each ITCR/DaSL google slides templates. 
The rest a person should be able to figure out just as they are filling out the templates.

**Comment by cansavvy** [comment]
Last step is https://github.com/jhudsl/ITCR_Course_Template_Leanpub/issues/23 and updating`transfer-rendered-files.yml` then I'll close this issue.
