### ISSUE TITLE
rgoogleslides refresh token DOES change

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/OTTR_Template#96]
https://github.com/jhudsl/DaSL_Course_Template_Bookdown/runs/2501410385?check_suite_focus=true

This error^ Is because authentication failed and it failed because now the refresh token is different than it was yesterday. 

SO, now I need to figure out if there's a way we can keep the refresh token github secret updated. Or if there's a way we can re-get the token whenever GHA is ran.

**Comment by cansavvy** [comment]
Do you have any ideas about this one, @muschellij2 ?

**Comment by cansavvy** [comment]
The access token appears stable though.

**Comment by muschellij2** [comment]
https://gargle.r-lib.org/articles/how-gargle-gets-tokens.html#credentials_user_oauth2

So I think first thing would be to try to refresh the token once it's in.  The question is whether if you get a refresh token you would need to push back a secret to github.

**Comment by muschellij2** [comment]
What about https://github.com/hmanzur/actions-set-secret

**Comment by cansavvy** [comment]
Will look into both these things!

**Comment by muschellij2** [comment]
I have https://github.com/muschellij2/aghast for github actions.  I added capabilities for secrets: https://github.com/muschellij2/aghast/commit/d97589a79dadd42f8c5ddf8cc20f286b78d75602 .  I didn't map all the endpoints, but have the ability to change secrets.

**Comment by cansavvy** [comment]
Tried this solution: https://github.com/jhudsl/DaSL_Course_Template_Bookdown/pull/97/files

**Comment by cansavvy** [comment]
I'm not sure now: 
https://github.com/jhudsl/DaSL_Course_Template_Bookdown/runs/2503470994?check_suite_focus=true

`Error: Refresh token not available`

**Comment by muschellij2** [comment]
Related to https://github.com/artemklevtsov/RGA/issues/22 ?

**Comment by muschellij2** [comment]
Should probably do a stop in case either of these are NULL:  https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/1f84f4c4116be58172290e16a37f3ed70ed8a64c/scripts/google_slides_image_linker.R#L69

**Comment by cansavvy** [comment]
> Should probably do a stop in case either of these are NULL:  https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/1f84f4c4116be58172290e16a37f3ed70ed8a64c/scripts/google_slides_image_linker.R#L69
> 

Will add this.

**Comment by cansavvy** [comment]
Aha! a clue! The token is being read as NULL https://github.com/jhudsl/DaSL_Course_Template_Bookdown/runs/2504500645?check_suite_focus=true !!!

**Comment by cansavvy** [comment]
YES! It's all working now!
